refactor: useExternalState의 setState를 개선한다
woowacourse-teams/2023-car-ffeine pull request #101
Opened 2023-07-16 13:46 UTC by kyw0716

## 📄 Summary
- [x] StateManager 클래스의 setState 메서드의 타입을 수정한다.
- [x] setState를 실행할 때 콜백함수가 전달 되었을 때, 새로운 state가 전달되었을 때를 분기처리하여 처리하도록 수정한다.
- [x] 콜백 함수가 전달되었을 때 인자로 this.state를 전달해준다.
- [x] 이전 값을 참조하기 위해 getStoreSnapShot을 사용했던 부분을 콜백함수 전달로 수정한다.

## 🙋🏻 More
> 실제 소요 시간: 30분

2023-07-16 18:18 UTC, gabrielyoon7 commented on frontend/src/utils/external-state/StateManager.ts
> +    if (param instanceof Function) {
if (param instanceof SetStateCallback<T>) {

은 불가능한가?

2023-07-16 18:20 UTC, gabrielyoon7 requested changes
잘 몰라서 질문한건데 한번 확인점

2023-07-17 04:09 UTC, kyw0716 commented on frontend/src/utils/external-state/StateManager.ts
> +    if (param instanceof Function) {
instanceof 우측에 들어오는 피 연산자는 생성자 함수여야 하는데 SetStateCallback<T>는 타입 제네릭이라 못들어오더라고

2023-07-17 05:43 UTC, gabrielyoon7 approved these changes

2023-07-17 05:53 UTC, feb-dain approved these changes
good

2023-07-17 08:46 UTC, merged