feat: 충전소와 충전기를 업데이트와 추가하는 기능을 구현한다 #84
woowacourse-teams/2023-car-ffeine pull request #104
Opened 2023-07-17 09:21 UTC by sosow0212

## 📄 Summary
> 충전소와 충전기가 변경 되었다면 업데이트를 하고, 추가 되었다면 새로 추가하는 기능을 만들었습니다.
아직 주기적으로 동작하는 기능은 없습니다.

## 🙋🏻 More
>

2023-07-17 10:39 UTC, drunkenhw requested changes
같이 페어로 했지만 혹시 뭔가 같이 실수 했을까봐 다시 확인해봤습니다~ 내일 같이 얘기해봐요

2023-07-17 10:39 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/Charger.java
> +    public boolean isUpdated(final Charger charger) {
final 제거해주세요~

2023-07-17 10:39 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/ChargerStatus.java
> +
개행 제거해주세요~

2023-07-17 10:39 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/ChargeStation.java
> +    public boolean equals(final Object o) {
final 제거해주세요~

2023-07-17 10:39 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/ChargeStation.java
> +    public boolean isUpdated(final ChargeStation station) {
ditto

2023-07-17 10:39 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/ChargeStation.java
> +
latitude, longitude 에 equals를 사용해도 좋을 것 같아요!

2023-07-17 10:39 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/ChargeUpdateJdbc.java
> +                .addValue("address", charger.getAddress())
charger에 address가 또 들어간 것 같아요..,,

2023-07-17 10:39 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/service/chargerstation/UpdateScrapper.java
> +
상수와 필드 변수와 구분해주세요~

2023-07-17 10:58 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/ChargeUpdateJdbc.java
> +                .addValue("address", charger.getAddress())
정말 컨플릭트 미쳐버리겠네요.. 🥲

2023-07-19 02:45 UTC, be-student approved these changes
이 부분만 바꿔주세요 👍 
고생 많으셨어요

2023-07-19 02:45 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ChargerStationUpdateService.java
> +                .collect(Collectors.toMap(ChargeStation::getStationId, it -> it));
Function.identity() 를 사용해도 좋을 것 같아요 it-> it 대신

2023-07-19 02:45 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ChargerStationUpdateService.java
> +        }
isEmpty 체크가 jdbc 쪽으로 가면 좋을 것 같아요
service 레벨에서 알 필요는 없을테니까요

2023-07-19 02:45 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ChargerStationUpdateService.java
> +    private final ChargeUpdateJdbc chargeUpdateJdbc;
JDBC 라는 구현체를 직접 알 필요는 없을 것 같아요
인터페이스를 한 단계 둬서, 추상화 하면 좋을 것 같아요

2023-07-19 04:48 UTC, kiarakim requested changes
instanceof는 꼭 바꾸라는 뜻은 아니고 comment인데 한번에 리뷰하니까 request changes로 리뷰할게요! 수고하셨습니다

2023-07-19 04:48 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/Longitude.java
>          }
instanceof 보다 객체에게 직접 물어보는 것도 고려해보면 좋을 것 같아요. 
instanceof는 컴파일시, 객체가 사용할 instanceof()는 런타임에 타입 에러를 체크한다고 하네요.

2023-07-19 04:48 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/service/chargerstation/UpdateScrapper.java
> +            chargers.add(chargeStation.getChargers().get(0));
여기 get(0)의 0이 어떤 것을 의미하는지 상수화하주면 좋을 것 같아요

2023-07-19 04:48 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/service/chargerstation/ChargerStationUpdateServiceTest.java
> +        );
여기선 assertAll 사용하고 ChargeUpdateJdpcTest에선 assertSoftly 사용하셨는데 통합하는 것은 어떨까유

2023-07-20 05:41 UTC, closed without merging