feat: 소셜 로그인을 구현한다
woowacourse-teams/2023-car-ffeine pull request #108
Opened 2023-07-18 04:33 UTC by drunkenhw

## 📄 Summary
>  소셜 로그인을 구현했습니다. 
나머지 자세한 설명은 조금 있다 작성하겠습니다

## 🙋🏻 More
>

2023-07-18 10:49 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/member/MemberRepository.java
> +
불필요한 개행 삭제해주세요~

2023-07-18 10:49 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/member/exception/MemberExceptionType.java
> +    INVALID_AUTH_PROVIDER(Status.UNAUTHORIZED, 2001, "지원하지 않는 로그인 플랫폼입니다"),
개행 한 칸 추가해주세요!

2023-07-18 10:51 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/member/oauth/OAuthMember.java
> +    String email();
잘 몰라서 그러는데 메서드명이 고정되어 있는건가요??
동사로 시작하면 더 좋을 것 같아서요!

2023-07-18 11:04 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/member/oauth/Provider.java
> +    GOOGLE("google", GoogleMember::new),
enum으로 관리하면서 값을 가져오는 건가요? 나중에 다른 oauth가 추가되어도 좋을 것 같네요  👍

2023-07-18 11:12 UTC, sosow0212 requested changes
작업하시느라 고생하셨습니다~
몇 가지의 컨벤션 관련된 리뷰와 코멘트 남겨놨습니다 👍

2023-07-18 11:12 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/infra/oauth/RestTemplateOAuthRequester.java
> +    public OAuthMember login(OAuthLoginRequest request) {
혹시 @Override 키워드를 제거하신 이유가 있나요?

2023-07-18 11:12 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/infra/oauth/RestTemplateOAuthRequesterTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
잘 몰라서 그러는데 혹시 DEFINED_PORT로 통합테스트하신 이유가 있으신가요?

2023-07-18 11:12 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/service/auth/AuthServiceTest.java
> +
불필요한 개행 삭제해주세요~

2023-07-18 11:12 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/service/auth/OAuthProviderPropertiesTest.java
> +
여기도 불필요한 개행 삭제해주세요!

2023-07-18 11:12 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/service/auth/AuthServiceTest.java
> +    void 소셜_로그인_후_회원을_반환한다() {
로그인 정보가 없다면 Repository를 이용해서 저장을 하는 로직이 있는데, 그것도 테스트 하면 더 좋을 것 같아요~

2023-07-19 04:41 UTC, be-student requested changes
화이팅!

2023-07-19 04:41 UTC, be-student commented on backend/src/test/java/com/carffeine/carffeine/infra/oauth/FakeGoogleController.java
> +    @PostMapping("/v4/token")
저희 버저닝 하는 것을 안 정했는데, v4 를 붙힌 기준은 무엇인가요?

2023-07-19 04:41 UTC, be-student commented on backend/src/main/resources/application.yml
> +      redirect-url: http://localhost:8080/login/oauth2/code/google
redirect uri 가 한 곳으로 고정되어있으면 추후에 테스트하기 어려울 것 같아요

ex) prod 서버에서 redirect 를 시킬 때, 우리 도메인/login~~~ 일 수도 있고
localhost/login 일 수도 있으니까요
유연하게 해주면 좋을 것 같아요 

이 부분만 더 유연하게 해주면 좋을 것 같아요

2023-07-19 04:46 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/infra/oauth/FakeGoogleController.java
> +    @PostMapping("/v4/token")
구글에서 이렇게 받는데요 제가 지정한 부분이 아니라 구글 api 주소라서 그렇습니다!

2023-07-19 05:13 UTC, kiarakim requested changes
Getter는 질문이고 test는 request changes 입니당

2023-07-19 05:13 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/service/auth/OAuthProviderProperties.java
> +    @Getter
클래스의 
@Getter랑 이 메서드의 @Getter는 다른가요?

2023-07-19 05:13 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/domain/member/oauth/ProviderTest.java
> +}
대소문자 틀린 이름을 검증하는 테스트도 하나 넣어주세염

2023-07-21 04:57 UTC, kiarakim approved these changes
수정할 건 없고 질문들입니다!
그 입력값의 대소문자 구분하는 테스트 부분만 고려해주십셔

2023-07-21 04:57 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/domain/member/exception/MemberExceptionType.java
> +    }
우리가 원래 갖고 있는 ChargeStationExceptionType이 있는데  MemberExceptionType 도 만들었네요. 그럼 나중에 다른 기능 있으면 예를 들어 "토큰 생성 및 검증" 기능이 있으면 그거에 대한 ExceptionType 구현 enum 만들면 될까욥

2023-07-21 04:57 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/infra/oauth/RestTemplateOAuthRequester.java
> +    }
여기 Token은 무슨 토큰인가유. 대면 설명해주세요

2023-07-31 07:53 UTC, be-student approved these changes
고생많으셨습니다 👍

2023-07-31 07:53 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/service/auth/AuthService.java
> +    private final OAuthRequester restTemplateOauthRequester;
이름이 restTemplateOauthRequester 라는 부분 대신 oauthRequester 로 바뀌면 더 좋을 것 같아요

2023-07-31 07:53 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/service/auth/dto/OAuthTokenResponse.java
> +        @JsonProperty("access_token")
자동으로 바뀌지 않나보네요 신기하네요 👍

2023-08-01 02:01 UTC, sosow0212 approved these changes
수고하셨습니다👍

2023-08-07 07:30 UTC, closed without merging