feat: 충전기 상태 및 혼잡도를 저장하는 기능을 구현한다
woowacourse-teams/2023-car-ffeine pull request #113
Opened 2023-07-18 08:20 UTC by kiarakim

## 📄 Summary
> 충전기 상태 및 혼잡도를 저장하는 기능을 구현합니다.

## 🙋🏻 More
>

2023-07-19 02:45 UTC, drunkenhw commented
https://github.com/woowacourse-teams/2023-car-ffeine/pull/69
여기도 같이 리뷰해야합니다~

2023-07-19 04:45 UTC, drunkenhw requested changes
수고하셨습니다

2023-07-19 04:45 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/ChargerState.java
> +
```suggestion
    public static ChargerState from(String input) {
        int num = Integer.parseInt(intput);
        return Arrays.stream(ChargerState.values())
                .filter(it -> it.value == num)
                .findAny()
                .orElse(STATUS_UNKNOWN);
    }

```

이런 방법은 어떤가요 그럼 관리할 필드가 하나 줄어서 나을 것 같아요

2023-07-19 04:45 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/congestion/PeriodicCongestion.java
> +            @JoinColumn(name = "charger_id", referencedColumnName = "charger_id", insertable = false, updatable = false, foreignKey = @ForeignKey(value = ConstraintMode.NO_CONSTRAINT))
```suggestion
  @JoinColumns(value = {
            @JoinColumn(name = "fk_station_id"),
            @JoinColumn(name = "fk_charger_id")
    }, foreignKey = @ForeignKey(ConstraintMode.NO_CONSTRAINT))
```

이렇게 하면 한번에 ForeignKey 를 해제할 수 있어요

2023-07-19 04:45 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/congestion/RequestPeriod.java
> +    private static final int UNIT = 100;
해당 클래스 필드,메서드, 상수들의 선언위치가 이상해요 수정부탁드립니다ㅓ

2023-07-19 04:45 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +public class RestTemplateChargeStationRequester implements ChargeStationRequester, ChargerStateRequester {
클래스 멋지네요 굿 👍

2023-07-19 04:45 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/infra/repository/ChargerStatusCustomRepositoryImpl.java
> +}
date time이 이상하게 들어오는 경우가 있었나요?
그렇다면 그 부분들도 parsing 할 수 있도록 만들어야겠네요

2023-07-19 04:45 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ChargerStatusCustomRepository.java
> +    void saveAll(List<ChargerStateRequest> item);
파라미터명이 모호하네요 ㅎ

2023-07-19 04:45 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/service/chargerstation/CongestionService.java
> +                .filter(it -> it.getCapacity().intValue() >= OUTPUT_THRESHOLD)
이 부분에 capacity가 null 일 경우도 있는데, 그 부분에 대해 처리도 해줘야할 것 같아요. 공공 API에서 옵셔널로 제공되더라고요. 그래서 `Charger` 클래스 내에 예를 들어 `isQuick()`이라는 메서드를 추가하는 것은 어떤가요?

2023-07-19 04:45 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/service/chargerstation/CongestionService.java
> +                .filter(it -> it.getCapacity().intValue() < OUTPUT_THRESHOLD)
ditto

2023-07-19 04:45 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/infra/repository/ChargerStatusRepositoryImplTest.java
> +    void 저장() {
테스트 메서드 이름을 좀 더 길게 적어주세요 ㅜ 무엇을 저장할까요.. ㅜ

2023-07-19 04:45 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/service/chargerstation/dto/RandomKeySelector.java
> +        int randomNumber = threadLocalRandom.nextInt(START_INDEX, serviceKeys.size());
근데 이 부분은 yml에 넣어놓은 key가 7개면 0~7 까지의 숫자가 랜덤으로 나오는 것 아닌가요? 
그렇게 된다면 7이라는 숫자가 나올 때 out of bound 가 발생할 것 같은데요. 
제가 잘못 이해했을 수도 있습니다.

2023-07-19 05:16 UTC, sosow0212 requested changes
작업하시느라 수고 많으셨습니다~
코멘트 몇 가지만 확인해주세요

2023-07-19 05:16 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/infra/repository/ChargerStatusCustomRepositoryImpl.java
> +        if (input == null || input.length() != 14) {
매직넘버 상수처리 해주세요~

2023-07-19 05:16 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ChargerStateRequester.java
> +    ChargerStateUpdateRequest requestChargerStatusUpdateRequest(int pageNo);
메서드 명을 `requestChargerStatusUpdate`로 바꾸는 건 어떨까요?

2023-07-19 05:16 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/congestion/IdGenerator.java
>          return dayOfWeek.getValue() * 10000L + startTime.getSection() + stationId + chargerId;
id값이 유니크한 값을 가지면서 데이터처럼 사용되네요👍 이 방법은 추후에 문제점은 없을까요?

2023-07-19 05:16 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/chargestation/charger/ChargerState.java
> +    COMMUNICATION_ERROR(1, "1"),
뒤에 `valueString`필드를 선언한 이유가 있나요?
메서드에서 `Integer.parseInt("...");`로 변경한 후에 비교해도 될 것 같아요~

만약 공공 API에서 null 값 혹은 빈 값이 오는 경우가 있어서 의도 했다면 무시하셔도 됩니다!

2023-07-19 05:16 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/service/chargerstation/ChargerStateUpdateService.java
> +    @Scheduled(cron = "0 0/7 * * * *")
주기적으로 업데이트가 되겠네요 👍

2023-07-20 03:20 UTC, sosow0212 approved these changes
작업하시느라 고생하셨습니다 👍

2023-07-20 03:20 UTC, drunkenhw approved these changes
수고하셨습니다

2023-07-20 03:21 UTC, merged