feat: 토큰 생성 및 검증 기능 구현
woowacourse-teams/2023-car-ffeine pull request #216
Opened 2023-07-27 03:46 UTC by kiarakim

## 📄 Summary
> OAuth에서 받아온 사용자를 저장한 상태에서
인증된 사용자의 id로 토큰 생성하는 기능과 토큰을 받았을 떄 그 토큰에서 id 추출해서 사용자 객체를 반환하는 기능을 구현했습니다.
우선 `api`는 임시로 작성한 것이고, `토큰 유효기간` 또한 논의해봐야 할 문제인 것 같습니다.

## 🕰️ Actual Time of Completion
>

## 🙋🏻 More
>

2023-07-27 04:41 UTC, drunkenhw requested changes
열심히 리뷰 달았습니다.
하지만 저희 우테코에서 spring security와 같은 기술은 아마 기술 검토에서 허락을 맡아야 사용가능한 것으로 알고있어서 해당 부분은 아마 수정해야할 것 같습니다.
수고하셨습니다!~

2023-07-27 04:41 UTC, drunkenhw commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-security'
spring security 라이브러리를 사용하면 안되는 것으로 알고 있는데 혹시 이 라이브러리를 빼고 구현할 수는 없을까요?

2023-07-27 04:41 UTC, drunkenhw commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
이 라이브러리도 빼는 것이 좋을 것 같습니다

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/config/AuthenticationConfig.java
> +public class AuthenticationConfig implements WebMvcConfigurer {
해당 클래스도 spring security의 클래스 같은데 제거되어야 할 것 같아요

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/security/SearchController.java
> +}
무슨 역할을 하는 컨트롤러인지 잘 모르겠습니다..

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/security/UserController.java
> +//        return ResponseEntity.ok().body(jwt);
주석은 제거 부탁드리겠습니다

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/AuthMemberResolver.java
> +        String token = authorization.substring(TOKEN_START_INDEX);
Token start index는 맞지만 만약 `Bearer ~!~~!~!~` 이런식이 아닌 
`Brrrrr ~!2121~`이런식의 토큰도 호환가능할 것 같은데 좀 더 사용자 인증과 관련된 부분이니 좀 더 빡빡하게 하는 것이 좋지 않을까요?

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/AuthMemberResolver.java
> +        return memberRepository.findById(memberId);
Member 도메인 객체를 반환하는 이유가 궁금합니다 순전히 궁금증입니다 알려주세요

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/JwtFilter.java
> +    private final String secretKey;
상수와 필드 사이의 개행 부탁드려요

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/JwtFilter.java
> +        SecurityContextHolder.getContext().setAuthentication(authenticationToken);
해당 부분은 어떻게 동작하는 것이죠?

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/JwtUtil.java
> +                .setExpiration(new Date(System.currentTimeMillis() + expiredMs))
Date를 LocalDateTime으로 사용하시지 않은 이유가 있나요?
https://docs.oracle.com/javase/8/docs/api/java/util/Date.html
Date는 Deprecate 됐다고 하네요

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/JwtUtil.java
> +public class JwtUtil {
Util이라는 네이밍보다 좀 더 괜찮은 것은 없을까요?
그리고 해당 클래스를 static 메서드를 가진 객체가 아닌 `@Component`로 등록하지 않으신 이유가 있을까요?

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/security/AuthService.java
> +    private String secretKey;
secret key가 JwtUtil이라는 클래스에 있는 것이 좀 더 유지보수에 좋을 것 같아요

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/security/AuthService.java
> +    private Long expiredMs = 1000 * 60 * 60L;
이 부분도요

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/security/AuthService.java
> +        return JwtUtil.createJwtById(id, secretKey, expiredMs);
갑자기 aaa라는 회원을 저장하는 이유가 뭔지 궁금해요

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/main/resources/application.yml
> +  secret: ${JWT_KEY}
이 key도 환경변수가 아닌 jasypt로 관리하는 것은 어떤가요

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/domain/security/MemberRepositoryTest.java
> +class MemberRepositoryTest {
중요한 어노테이션이 클래스이름이랑 더 가깝게 왔으면 좋겠어요

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/domain/security/MemberRepositoryTest.java
> +    }
setup으로 해당 member를 저장하는 이유가 있나요?

2023-07-27 04:41 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/infrastructure/api/JwtUtilTest.java
> +    }
테스트가 3초간 쉬는 것은 비효율적인 것 같아요 시간을 더 짧게 가져가는 방법은 어떠신가요?

2023-07-27 08:09 UTC, sosow0212 requested changes
작업하시느라 수고하셨습니다👍
스프링 시큐리티를 사용하셔서.. 다시 덜어내고 작업 하셔야할 것 같아요 ㅠㅠ
남긴 리뷰 몇 가지 확인해주세요~

2023-07-27 08:09 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/controller/security/SearchController.java
> +    @PostMapping
개행 추가해주세요~

2023-07-27 08:09 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/controller/security/UserController.java
> +        String jwt = authService.makeJwt();
사용자의 정보는 없어도 될까요?

2023-07-27 08:09 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/domain/security/MemberRepository.java
> +    Member findByEmail(String email);
반환형이 `Optional<Member>`가 되면 어떨까요? 혹시 `Member`로 반환형을 주는 이유가 있을까요?

2023-07-27 08:09 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/JwtFilter.java
> +        Long id = JwtUtil.extractId(token, secretKey);
JwtUtil을 빈으로 등록해서 사용하는 것은 어떨까요?

2023-07-27 08:09 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/config/AuthenticationConfig.java
> +    public SecurityFilterChain securityFilterChain(HttpSecurity httpSecurity) throws Exception {
ㅠㅠ 스프링 시큐리티네요.. 나중에 제거하시고 필터로 직접 만들어주세요~

2023-07-27 08:09 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/config/AuthenticationConfig.java
> +@Configuration
@Configuration의 위치가 클래스 바로 위로 가는 건 어떨까요?
중요한 어노테이션일수록 클래스 이름과 가깝게요

2023-07-28 12:41 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/config/AuthenticationConfig.java
> +public class AuthenticationConfig implements WebMvcConfigurer {
제거했어여

2023-07-29 05:13 UTC, be-student approved these changes
아주 고생 많으셨어요 👍 
처음 하는 작업이라서 정말 힘들었을 텐데 잘 해주셨네요

2023-07-29 05:13 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/station/controller/auth/MemberController.java
> +    public ResponseEntity<String> createJwt() {
임시 api 인 것 같아요!
제거하면 좋지 않을까요?

2023-07-29 05:13 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/station/controller/auth/SearchController.java
> +    @PostMapping
- 한줄을 띄면 좋을 것 같아요!

2023-07-29 05:13 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +        response.sendError(HttpServletResponse.SC_UNAUTHORIZED, errorMessage);
여기에 직접 body 를 넣어줄 수 있는데요
message 만 전달하는 것이 아니라
백엔드에서 사용하는 errorResponse 였나 하는 그 클래스를 사용하면 어떨까요?

2023-07-29 05:13 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/station/domain/jwt/JwtProvider.java
> +        return Date.from(now.plusHours(1).atZone(ZoneId.systemDefault()).toInstant());
추후에 1시간이라는 부분은 yml 로 관리하게 된다면 더 유연하게 사용할 수 있을 것 같아요

2023-07-29 10:27 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/security/UserController.java
> +        String jwt = authService.makeJwt();
사용자 정보는 로그인서비스에서 member 객체 만드는데 거기서 바로 jwt 만들면 돼서요..!

2023-07-29 10:28 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/security/MemberRepository.java
> +    Member findByEmail(String email);
이미 로그인 되어 DB에 저장한 사람의 토큰을 검증할 때만 사용해서 Optional를 고려하지 않았는데 제가 생각못한 반례가 있을까욥

2023-07-31 07:45 UTC, sosow0212 approved these changes
처음하는 작업이라 힘드셨을텐데 수고 많으셨습니다. 👍

2023-07-31 08:22 UTC, drunkenhw requested changes
리뷰 남겼습니다 감사합니다~

2023-07-31 08:22 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/config/AuthenticationConfig.java
> +public class AuthenticationConfig implements WebMvcConfigurer {
Authentication Config라는 클래스 이름보다 그냥 WebConfig 이용해서 좀 더 유연한 클래스처럼 보이는 것도 좋을 것 같아요!

2023-07-31 08:22 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +        String token = authorization.substring(TOKEN_START_INDEX);
```suggestion
        String token = authorization.substring(BEARER_PREFIX.length());
```
이 방식은 어떠신가요?

2023-07-31 08:22 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +        response.sendError(HttpServletResponse.SC_UNAUTHORIZED, errorMessage);
동감합니다

2023-07-31 08:22 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +        }
이 부분을 if로 validation 할 때 `sendUnauthorizedError` 을 호출하는 것은 어떤가요?

2023-07-31 08:22 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +    private final String secretKey;
secret key 를 한 곳에서 관리하는 것이 어떤가요?

2023-07-31 08:22 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/jwt/JwtProvider.java
> +public class JwtProvider {
jwt provider와 jwt 클래스가 나뉘어져있는 이유가 뭔가요?

2023-07-31 08:22 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/exception/AuthorizationException.java
> +    }
개행 부탁드려요

2023-07-31 08:22 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/exception/StationExceptionType.java
> +    NO_AUTHORIZATION(Status.INVALID, 1004, "토큰의 권한이 없습니다.");
station Exception에  권한이 없다는 것은 이상한 것 같아요

2023-07-31 08:22 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/AuthMemberResolver.java
> +    private String secretKey;
secret key가 한 군데에서 관리하면 좋을 것 같아요

2023-07-31 10:11 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/jwt/JwtProvider.java
> +public class JwtProvider {
그러게요. 붙여주었습니다.

2023-07-31 10:13 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +        }
좋네요. 이런건 어떻게 알고 리뷰해주신거죠👍

2023-08-01 02:01 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/AuthMemberResolver.java
> +    private String secretKey;
한곳에서 관리하도록 했습니다.

2023-08-01 02:01 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/exception/StationExceptionType.java
> +    NO_AUTHORIZATION(Status.INVALID, 1004, "토큰의 권한이 없습니다.");
없앴어요

2023-08-01 02:01 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/exception/AuthorizationException.java
> +    }
네 했어요

2023-08-01 02:01 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +    private final String secretKey;
한곳에서 관리하도록 했습니다.

2023-08-01 02:02 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +        }
넴 반영완ㅇ료

2023-08-01 02:02 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +        String token = authorization.substring(TOKEN_START_INDEX);
좋아요

2023-08-01 02:03 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/jwt/JwtProvider.java
> +        return Date.from(now.plusHours(1).atZone(ZoneId.systemDefault()).toInstant());
햇어요

2023-08-01 02:04 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/auth/SearchController.java
> +    @PostMapping
이 클래스는 바람속으로 사라졌습니다. 감사합니다

2023-08-01 02:04 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/auth/MemberController.java
> +    public ResponseEntity<String> createJwt() {
넴. 나중에 머지되면 사라진 클래스지만 제거하겟습니다

2023-08-01 02:04 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/config/AuthenticationConfig.java
> +@Configuration
넵 감사합닏

2023-08-01 02:05 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/config/AuthenticationConfig.java
> +    public SecurityFilterChain securityFilterChain(HttpSecurity httpSecurity) throws Exception {
네ㅠㅠ 반여완요

2023-08-01 02:05 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/JwtFilter.java
> +        Long id = JwtUtil.extractId(token, secretKey);
해당 클래스는 삭제됐고 위 기능을 Jwt 클래스가 하고있어욥

2023-08-01 02:05 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/security/SearchController.java
> +    @PostMapping
넹. 근데 사라진 클래스..ㅠㅠ

2023-08-01 02:38 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +        response.sendError(HttpServletResponse.SC_UNAUTHORIZED, errorMessage);
반영햇습지다

2023-08-01 02:38 UTC, kiarakim commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-security'
뺐어요

2023-08-01 02:38 UTC, kiarakim commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
뺏어요

2023-08-01 02:39 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/config/AuthenticationConfig.java
> +public class AuthenticationConfig implements WebMvcConfigurer {
녜에

2023-08-01 02:39 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/security/SearchController.java
> +}
사라진 클래스입니다

2023-08-01 02:39 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/AuthMemberResolver.java
> +        String token = authorization.substring(TOKEN_START_INDEX);
startsWith으로 확인해주었습니다

2023-08-01 02:39 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/JwtFilter.java
> +    private final String secretKey;
넵

2023-08-01 02:40 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/JwtFilter.java
> +        SecurityContextHolder.getContext().setAuthentication(authenticationToken);
잘 몰라서 제거했습니다

2023-08-01 02:40 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/api/JwtUtil.java
> +public class JwtUtil {
Bean을 잘 몰랐어서.. 이 클래스는 사라졌습니다

2023-08-01 02:40 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/security/AuthService.java
> +    private String secretKey;
네 고쳤습니다

2023-08-01 02:41 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/security/AuthService.java
> +    private Long expiredMs = 1000 * 60 * 60L;
yml 파일에 암호화해놨습니다

2023-08-01 02:41 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/security/AuthService.java
> +        return JwtUtil.createJwtById(id, secretKey, expiredMs);
임시 데이터였는데 push할 때 잊었던 것같ㅇ아요 . 주의하겠ㅅ브니ㅣ다

2023-08-01 02:45 UTC, kiarakim commented on backend/src/main/resources/application.yml
> +  secret: ${JWT_KEY}
그럼 key를 key로 암호화하는건데 고건 생각 못했네요. 괜찮은 것같아요.

2023-08-01 02:52 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/domain/security/MemberRepositoryTest.java
> +class MemberRepositoryTest {
네에

2023-08-01 05:59 UTC, drunkenhw requested changes
열심히 리뷰했습니다 감샇반디ㅏ

2023-08-01 05:59 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +        Jwt jwt = new Jwt();
Jwt 클래스는 component인데 굳이 new 로 생성해주지말고 빈으로 주입하는 것이 좋아보여용

2023-08-01 05:59 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +        return memberRepository.findById(id)
member가 존재한다는 부분은 exists라는 메서드로 하면 좋을 것 같아요

2023-08-01 05:59 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +            filterChain.doFilter(request, response);
여기도 sendError~~~ 해주면 좋을 것 같아요

2023-08-01 05:59 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +            filterChain.doFilter(request, response);
멤버가 존재한다면 에러? 로직이 반대로 된 거 같아요

2023-08-01 05:59 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/jwt/Jwt.java
> +        Key key = gethmacShaKey();
Key는 한번만 만들 수 없나요?

2023-08-01 07:08 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +        Jwt jwt = new Jwt();
녜에

2023-08-01 07:10 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +        return memberRepository.findById(id)
넹

2023-08-01 07:10 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +            filterChain.doFilter(request, response);
그러게요 이건 제가 왜 그랬을까요

2023-08-01 07:12 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/jwt/Jwt.java
> +        Key key = gethmacShaKey();
이거 한번만 만든건디 이거 메서드에여

2023-08-01 07:25 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/jwt/Jwt.java
> +        Key key = gethmacShaKey();
아니네요. 고쳣습ㄴ디ㅏ

2023-08-01 07:38 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/filter/JwtFilter.java
> +            filterChain.doFilter(request, response);
했습니다 감사합니다

2023-08-01 07:39 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/security/UserController.java
> +//        return ResponseEntity.ok().body(jwt);
넵

2023-08-01 07:45 UTC, drunkenhw approved these changes
키아라수고하셨습니다고생하셧습니다리뷰많이해서죄송합니다

2023-08-01 07:46 UTC, merged