feat: 충전기 상태에 대한 정보를 분리한다
woowacourse-teams/2023-car-ffeine pull request #30
Opened 2023-07-05 12:07 UTC by drunkenhw

## 📄 Summary
> 충전기의 현재 상태를 가지고 있는 테이블을 분리했습니다.

## 🙋🏻 More
>

2023-07-05 14:36 UTC, be-student requested changes
화이팅 어려우면 내일 아침에 물어봐

2023-07-05 14:36 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/dto/ChargeStationInfoRequest.java
>      }
오 메서드 분리 굿! 👍

2023-07-05 14:36 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargerStatus.java
> +}
private LocalDateTime startTimeWhenCharging;
이 부분은 안 들어가도 괜찮나요?

2023-07-05 14:36 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/domain/Charger.java
> +    private ChargerStatus chargerStatus;
이런 방향은 어떤가요?
```mermaid
graph TD;
ChargeStation --> Charger
ChargeStation --> ChargerStatus
```
Charger 와 ChargerStatus 가 서로 모르는 상황이라면 어떻게 될 것 같은가요?


혹은
```mermaid
graph TD;
ChargeStation --> Charger
ChargerStatus --> Charger
```
이런 구조는 어떤가요?
ChargerStatus 가 외래키가 있음

현재 구조상으로 문제가 생길 수 있는게

지금 구조대로라면, 외래키가 Charger 쪽에 있어서, charger 가 로딩되면 무조건 chargerStatus 가 로딩이 되는데요
전체 충전소와 충전기 데이터를 업데이트 하는 과정에서 불필요하게 chargerStatus 가 로딩될 것 같아요

2023-07-05 14:40 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargerStatus.java
> +}
네 필요없는 정보입니다

2023-07-05 14:51 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/Charger.java
> +    private ChargerStatus chargerStatus;
1번도 나쁘지 않아보이는데 도메인적으로 봤을 때 이상하지 않은가요? Charger의 id를 찾아 charger station에서 charge의 상태에 대한 정보를 꺼낸다는 점이?
2번은 charger가 charge station을 들고 있는다는게 더 이상하지 않을까요? 같은 충전소에 충전기마다 Charge Station 정보는 같을 텐데 매번 조회 시 charge station을 조회해야하지 않나요? 
그리고 누누가 얘기한 
`지금 구조대로라면, 외래키가 Charger 쪽에 있어서, charger 가 로딩되면 무조건 chargerStatus 가 로딩이 되는데요
전체 충전소와 충전기 데이터를 업데이트 하는 과정에서 불필요하게 chargerStatus 가 로딩될 것 같아요`
이 부분은 전체 충전소와 충전기 데이터를 업데이트 하는 과정에 charger status를 같이 업데이트 해주면 해결될 수 있는 문제이지 않을까요?

2023-07-05 14:55 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/domain/Charger.java
> +    private ChargerStatus chargerStatus;
아까 정했을 때, 전체 충전소와 충전기 데이터를 업데이트 할 때, chargerStatus 를 업데이트 하지 않기로 결정했던 것 같아서요 👍

2023-07-05 14:58 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/domain/Charger.java
> +    private ChargerStatus chargerStatus;
chargerStatus는 항상 업데이트 대상 아니었나요..? 
*전체 충전소와 충전기 데이터를 업데이트 할 때*가 어느 주기를 말씀하는거져

2023-07-05 14:59 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/domain/Charger.java
> +    private ChargerStatus chargerStatus;
하루에 한 번 정도씩 도는 전체 충전기에 대한 데이터 변경과, 전체 충전소에 대한 업데이트요

2023-07-05 15:02 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/Charger.java
> +    @OneToOne(cascade = CascadeType.ALL)
이 부분은 어차피 `Charger` 객체를 조회할 때 `ChargerStatus`가 필요해서 즉시 로딩 하도록 만든 것 맞죠? 👍

2023-07-05 15:04 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargerStatus.java
> +
헷갈려서 그러는데 현재 Charger는 stationId와 chargerId를 갖고 있는데 그 chargerId가 또 stationId와 chargerId를 갖고있는건가여?

2023-07-05 15:40 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/Charger.java
> +    private ChargerStatus chargerStatus;
혹은 Lazy loading을 사용하면 굳이 충전기 상태 정보는 안불러올 수 있을 것 같아요 그렇게 하려면 연관관계를 `@OneToMany`로 바꿔주면 될 것 같네요

2023-07-06 07:04 UTC, sosow0212 approved these changes
요구 사항에 맞게 설계를 잘 바꿔주셨네요 👍👍

2023-07-06 07:06 UTC, be-student approved these changes
고생 많았어 👍 🚗

2023-07-06 07:07 UTC, kiarakim approved these changes
이해하기 쉽게 반영해주셨네요!👍

2023-07-06 07:08 UTC, merged