refactor: 충전소 업데이트하는 로직 페이징 처리한다
woowacourse-teams/2023-car-ffeine pull request #352
Opened 2023-08-03 12:52 UTC by drunkenhw

[#351]

## 📄 Summary
> 페이징 처리 했습니다

## 🕰️ Actual Time of Completion
> 3시간

## 🙋🏻 More
> 

close #351

2023-08-08 06:57 UTC, kiarakim requested changes
수고하셨어요.👍 
매직넘버랑 쿼리부분만 수정하면 될 것 같아요.

2023-08-08 06:57 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/station/StationRepository.java
> +    List<Station> findAllByPaging(@Param("stationId") String stationId, Pageable pageable);
40번쨰 줄의 :stationId는 41번째 줄의 파라미터 stationId인가요?
이부분은 잘 몰라서..ㅎ

2023-08-08 06:57 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationUpdateService.java
> +        return savedStations.get(savedStations.size() - 1).getStationId();
여기 상수화 해주면 좋을 것 같아요

2023-08-08 06:58 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/StationRepositoryImpl.java
> +        String sql = "INSERT IGNORE INTO charge_station (station_id, station_name, company_name, address, is_parking_free, operating_time, detail_location, latitude, longitude, is_private, contact, s
생각만 하고 말을 안했네요. 여기 created_at이랑 updated_at 넣어줘서 아마 conflict 날 것같아여

2023-08-14 04:33 UTC, sosow0212 approved these changes

2023-10-08 06:36 UTC, closed without merging