refactor: 생성일과 수정일을 추가한다.
woowacourse-teams/2023-car-ffeine pull request #374
Opened 2023-08-06 16:31 UTC by kiarakim

## 📄 Summary
> refactor: 생성일과 수정일을 추가한다.

## 🕰️ Actual Time of Completion
> 20m

## 🙋🏻 More
>

2023-08-06 16:35 UTC, drunkenhw requested changes
해당 칼럼이 두개가 늘어서 아마 jdbctemplate을 사용하는 부분도 전부 수정해줘야할 것 같아요 해당 부분들도 확인 부탁드려요

2023-08-06 16:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/member/domain/Member.java
> +import lombok.*;
import 의 * 부분은 수정 됐으면 좋겠습니다

2023-08-06 16:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/BaseTime.java
> +    @CreatedDate
개행 부탁드려요 그리고 클래스 이름 BaseEntity는 어떤가요?

2023-08-06 16:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/charger/Charger.java
> +import javax.persistence.*;
ditto

2023-08-06 16:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/charger/ChargerStatus.java
> +import javax.persistence.*;
ditto

2023-08-06 17:03 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/member/domain/Member.java
> +import lombok.*;
아 넵. 인텔리제이 새로 설치했더니 이전에 설정해둔게 다 없어졌네용ㅇ. 고쳤습니다.

2023-08-06 17:11 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/charger/Charger.java
> +import javax.persistence.*;
녜

2023-08-06 17:11 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/charger/ChargerStatus.java
> +import javax.persistence.*;
녜

2023-08-06 17:11 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/BaseTime.java
> +    @CreatedDate
좋아요.

2023-08-07 07:48 UTC, drunkenhw requested changes
모르는 거 질문 남겼습니다 컨벤션 확인해주세요

2023-08-07 07:48 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/BaseEntity.java
> +    @NotNull
개행 해주세요

2023-08-07 07:48 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/BaseEntity.java
> +    }
이 부분이 필요한 이유가 궁금해요

2023-08-07 07:48 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/BaseEntity.java
> +    }
pre update가 뭐죠?

2023-08-07 07:48 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/ChargerRepositoryImpl.java
> +                .addValue("updatedAt", charger.getUpdatedAt());
get UpdatedAt 을 하면 어느 시점이죠? 언제 날짜가 찍힐까요?

2023-08-07 07:55 UTC, be-student approved these changes
박스터가 말한 부분만 고치면 될 것 같아요! 👍

2023-08-07 08:01 UTC, sosow0212 approved these changes
위에 리뷰 잘 남겨주셔서 그것만 고치고 머지 해주셔도 될 것 같습니다 !

2023-08-07 08:03 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/BaseEntity.java
> +    @NotNull
네에

2023-08-07 08:03 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/BaseEntity.java
> +    }
영속 상태의 entity의 내용이 수정되면, @PreUpdate 어노테이션에 의해서 updatedAt의 값이 LocalDateTime.now()로 갱신될거라 생각했는데 그게 아니라 @PreUpdate가 선언되어 있는 메소드는 실제 DB에 쓰기 SQL이 커밋되기 직전에 수행된다고 하네요. 
잘못 알고 쓴 경우임다. 다른 방법으로 변경하려고요.

2023-08-07 08:03 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/ChargerRepositoryImpl.java
> +                .addValue("updatedAt", charger.getUpdatedAt());
음~ createdAt 보다 한 8초정도 뒤에 찍히네요. BaseEntity의 created_at 컬럼에 @CeatedDate쓰면 달라질 것 같아요. 수정하려고요

2023-08-07 08:15 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/BaseEntity.java
> +    }
이제 필요없어요

2023-08-07 08:49 UTC, drunkenhw approved these changes
이것만 알려주세요 수고하셨습니다~

2023-08-07 08:49 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/MockBeanInjection.java
> +@MockBean(JpaMetamodelMappingContext.class)
얘는 뭐하는 건가요?

2023-08-08 02:20 UTC, merged

2023-08-08 02:21 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/MockBeanInjection.java
> +@MockBean(JpaMetamodelMappingContext.class)
- @MockBean(JpaMetamodelMappingContext.class)

    JPA metamodel must not be empty!

    @WebMvcTest로 테스트를 진행하면서 마주한 에러다. 해석하면, JPA 메타 모델은 비워둘 수 없다는 말이다. 알아보니 @WebMvcTest는 JPA 관련 Bean을 로드하지 않는 테스트 어노테이션이기 때문에 위의 @EnableJpaAuditing과 같은 Jpa Auditing 기능을 사용할 땐 컨트롤러 테스트 클래스 위에 이 어노테이션을 붙이면 된다.