feat: 소셜로그인을 구현한다
woowacourse-teams/2023-car-ffeine pull request #384
Opened 2023-08-07 07:44 UTC by drunkenhw

## 📄 Summary
>  키아라가 만들어놓은 jwt 를 이용해서 소셜 로그인이 성공하면 토큰을 발급하도록 변경했습니다. 먼저 흐름은 
1. 프론트에서 원하는 벤더사의 이름과, redirect uri를 받아옵니다.
2. 서버에서는 받은 정보들로 해당 벤더사의 로그인 uri를 제공합니다
3. 프론트에서 로그인에 성공하면 벤더사에서 받아온 code와 redirect uri를 받습니다.
4. 받고 벤더사와 통신하여 정보를 받고 저장합니다
5. jwt를 리턴 해줍니다.

## 🕰️ Actual Time of Completion
>5시간

## 🙋🏻 More
>

2023-08-07 08:00 UTC, sosow0212 requested changes
작업하시느라 수고하셨습니다~ 기능적으로는 잘 해주신 것 같아서 컨벤션에 대해 몇 가지 남겼습니다.

2023-08-07 08:00 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/auth/domain/TokenProvider.java
> +
불필요한 개행은 없애줘도 될 것 같습니다.

2023-08-07 08:00 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/auth/infrastructure/RestTemplateOAuthRequester.java
> +        return UriComponentsBuilder.fromUriString(providerProperties.getLoginUrl())
`fromUriString`보다는 차라리 from은 어떨까요? String인 걸 알 필요가 있을까 싶어서요

2023-08-07 08:00 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/auth/infrastructure/RestTemplateOAuthRequester.java
> +        headers.setContentType(MediaType.APPLICATION_FORM_URLENCODED);
어떤 행위인지 메서드를 한 번 분리해줘도 좋을 것 같아요

2023-08-07 08:00 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/auth/infrastructure/RestTemplateOAuthRequester.java
> +        headers.setContentType(MediaType.APPLICATION_JSON);
여기도 마찬가지입니다~

2023-08-07 08:00 UTC, sosow0212 commented on backend/src/main/resources/application-prod.yml
> +
개행 없애줘도 될 것 같아요!

2023-08-07 08:00 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/auth/domain/ProviderTest.java
> +                .hasMessage("지원하지 않는 로그인 플랫폼입니다");
`Enum.getMessage()`로 메시지 검증하는 건 어떨까요?

2023-08-07 08:00 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/auth/infra/FakeGoogleController.java
> +    public OAuthTokenResponse token(
어떤 행위인지 구체적으로 네이밍해주면 더 좋을 것 같아요

2023-08-07 08:00 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/auth/infra/FakeGoogleController.java
> +                redirectUri.equals("http://localhost:8080/")) {
이 부분도 메서드 분리를 통해서 어떤 행위인지 명시해주면 좋을 것 같습니다

2023-08-07 08:00 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/auth/service/OAuthProviderPropertiesTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
👍

2023-08-07 08:00 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/fake/member/FakeMemberRepository.java
> +    private final Map<Long, Member> map = new HashMap<>();
개행 한 칸 추가해주세요

2023-08-07 08:08 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/auth/infrastructure/RestTemplateOAuthRequester.java
> +        return UriComponentsBuilder.fromUriString(providerProperties.getLoginUrl())
해당 클래스는 제가 다른 라이브러리라서 어쩔 수 없었습니다

2023-08-08 03:46 UTC, be-student approved these changes
이 부분만 수정해주시면 좋을 것 같아요 👍

2023-08-08 03:46 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/auth/controller/AuthController.java
> +    }
이 요청이 post 인 이유가 있으신가요?

2023-08-08 03:46 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/auth/domain/OAuthMember.java
> +    String imageUrl();
imageUrl 이 모든 provider 에 있는 정보인가요?

2023-08-08 03:46 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/auth/infrastructure/RestTemplateOAuthRequester.java
> +        return responseEntity.getBody();
getForObject 같은 방식으로 해도 좋을 것 같아요

2023-08-08 03:46 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/auth/service/AuthService.java
> +    }
Transactional 의 범위가 살짝 큰 것 같아요
request 를 하는 부분을 transactional 의 범위에서 제거해야 될 것 같아요

2023-08-08 03:52 UTC, kiarakim approved these changes
어프룹할게요. 수고하셨어요 한가지만 수정해주세요~

2023-08-08 03:52 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/auth/controller/AuthController.java
> +@RequestMapping("/api")
우리 api 그거 빼기로 하지 않았나요?

2023-08-08 03:52 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/auth/controller/AuthFilter.java
> +        response.setContentType(MediaType.APPLICATION_JSON_VALUE);
이 둘의 차이가 뭐에요??

2023-08-08 03:52 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/auth/controller/AuthMemberResolver.java
> +    public Long resolveArgument(
tokenProvider.extract(token);
이 메서드는 Long을 반환하는데 확장성을 위해 반환타입을 Object로 하신건가요?
궁금궁금

2023-08-08 04:07 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/auth/controller/AuthController.java
> +    }
그러게요 수정했습니다~

2023-08-08 04:08 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/auth/domain/OAuthMember.java
> +    String imageUrl();
네 구글, 카카오, 네이버, 정도로 저희가 사용할 것 같은데 이 3개의 벤더사 그리고 깃헙에도 제공되는 것으로 알고있습니다.

2023-08-08 04:11 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/auth/controller/AuthController.java
> +@RequestMapping("/api")
그렇네요 제거하겠습니다

2023-08-08 04:12 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/auth/controller/AuthFilter.java
> +        response.setContentType(MediaType.APPLICATION_JSON_VALUE);
Enum과 글자?

2023-08-08 04:12 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/auth/controller/AuthMemberResolver.java
> +    public Long resolveArgument(
Long을 반환하도록 변경한건데요..

2023-08-08 05:03 UTC, sosow0212 approved these changes
수고하셨습니다 !!

2023-08-08 05:05 UTC, gabrielyoon7 approved these changes

2023-08-08 05:06 UTC, kyw0716 approved these changes
굿샷

2023-08-08 05:06 UTC, merged