feat: 리뷰 댓글 CRUD 기능을 구현한다
woowacourse-teams/2023-car-ffeine pull request #428
Opened 2023-08-10 00:42 UTC by kiarakim

## 📄 Summary
> feat: 리뷰 댓글 CRUD 기능을 구현한다

## 🕰️ Actual Time of Completion
> 6시간

## 🙋🏻 More
>

2023-08-10 01:35 UTC, sosow0212 requested changes
작업하시느라 수고하셨습니다!
코멘트 확인해주세요~

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +    @PostMapping("/api/reviews/{reviewId}")
yml에서 api 경로를 붙여줘서 여기에 api 빼도 될 것 같습니다!

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +    @DeleteMapping("/api/reviews/{reviewId}")
여기도 빼주세요~

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +import javax.persistence.*;
import 와일드카드 빼주세요~

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    private long id;
Long이 아니고 long으로 작성하신 이유가 있을까요?

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +}
마지막에 개행이 없나봐요!

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/ReviewRepository.java
> +    Review findById(Long reviewId);
id 기준으로 찾아올 때 Review가 없다면 예외를 어떻게 찾을까요?
`Optional<Review> findById(Long reviewId);`
로 바꿔주면 더 좋을 것 같아요~

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/exception/review/ReviewExceptionType.java
> +    INVALID_RATINGS_NOTNULL(Status.INVALID, 2001, "별점은 null이 될 수 없습니다"),
`NOT_NULL`이 컨벤션에는 더 맞을 것 같습니다!

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/exception/review/ReviewExceptionType.java
> +
불필요한 개행 제거해주세요

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +    private void validateRequest(CreateReviewRequest request) {
이 검증은 서비스말고 Controller에서 들어오는 Dto에 대해서 @Valid로 해보는 건 어떨까요?
애초에 데이터가 검증 후에 서비스에 들어오게요! 혹은 도메인에서도 같이해도 되겠네요

예전에 고민했던 내용인데 저는 주로 @Valid로 Dto에서도 검증하고, 데이터베이스에 들어가는 도메인에서도 한 번 더 해주는데 고민해보시고 자신의 기준을 가져보는 것도 좋을 것 같습니다!

그렇게 된다면 서비스 레이어에서는 불필요한 상수를 관리할 필요도 없고 로직에 집중할 수 있을 것 같아요

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +        if (!review.getMemberId().equals(memberId)) {
`review.getMemberId().equals(memberId)` 이 부분을 도메인 로직으로 뺄 수 있지 않을까요?

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/station/domain/review/ReviewRepositoryTest.java
> +}
여기도 개행이 없네요!

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/station/domain/review/ReviewRepositoryTest.java
> +        String stationId = "ME101010";
`stationId`를 given으로 올리고 builder부분에서도 사용하고 when부분에서도 사용할 수 있을 것 같아요

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +                .hasMessage("리뷰 내용은 null이 될 수 없습니다");
하드코딩된 값으로 검증하는 것이 아닌 ExceptionType.getMessage 를 호출해서 코드로 검증해보는 건 어떨까요?
그렇게 된다면 Exception의 값이 바뀌더라도 테스트는 성공할 것 같습니다

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +        CreateReviewRequest request = new CreateReviewRequest(4, "이상은 인간에 실로 만천하의 아니다. 대중을 피가 이 보는 심장은 꽃이 역사를 일월과 만천하의 봄바람이다. 피고, 기쁘며, 뼈 길지 속에서 이상이 싸인 황금시대다. 가진 같으며, 풀밭에 이것이다. 보내는 우는 산야에 인생을 부패를 뿐이다.
ㅋㅋㅋㅋㅋ

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +}
여기도 개행 추가해주세요~

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    private Long memberId;
Member와 연관관계를 안 맺어주신 이유가 있을까요?

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    private String stationId;
이 부분도 연관관계를 안 맺어주신 이유가 궁금합니다!

2023-08-10 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +        return reviewsByPage(allByStationId, page);
전체 조회를 하고 페이징 처리를 해주는 것으로 보입니다
다르게 바꿔보는 것은 어떨까요? (ex. page == 0, 5개만 db에서 가져오고 nextPage가 있는지 알려주기)

지금 구조면
1페이지 조회시 `DB에서 모두 조회` -> `코드로 페이징 처리`
2페이지 조회시 `DB에서 모두 조회` -> `코드로 페이징 처리`

이렇게 불필요한 DB 전체 조회가 있네요!

2023-08-10 01:35 UTC, drunkenhw requested changes
리뷰 남겼습니다~ 수고하셨습니다 👍

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +        return ResponseEntity.noContent().build();
왜 noContent를 반환하나여? 궁금

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +    public ResponseEntity<Void> updateReview(
수정인데 post인 이유가 있나여

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +    public ResponseEntity<Void> updateReview(
그리고 저희 앞에 api prefix 지워도 될 것 같아요

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +    @DeleteMapping("/api/reviews/{reviewId}")
ditto

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponse.java
> +public record ReviewResponse(Long reviewId,
얘도 개행 부탁드려요
그리고 빌더 어노테이션을 사용하신 이유가 있나요? 사용하는 곳이 없어보여서요
```suggestion
public record ReviewResponse(
          Long reviewId,
```

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +public class Review extends BaseEntity {
equals and hashcode 재정의 부탁드려요

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    }
https://velog.io/@jsb100800/Spring-boot-JPA-Soft-Delete-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0
한번 참고해보시는 것이 어떨까요

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    private Long memberId;
왜 Member 객체, station 객체가 아니라 id만 가지고 있나요?

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    private long id;
얘는 왜 primitive type인가요?

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/exception/review/ReviewExceptionType.java
> +    UNAUTHORIZED_MEMBER(Status.UNAUTHORIZED, 2006, "리뷰 작성자와 수정자가 다릅니다");
cmd + shift+ L
부탁드려요

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +    }
이 검증은 도메인 객체에서 하는 것이 어떤가요

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +        List<Review> allByStationId = reviewRepository.findAllByStationId(stationId);
paging 하지않고 findAll로 하신 이유가 있나요?

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +        return review;
개행 하신 이유가 있나요 조금 보기 불편해서ㅓ요

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/dto/CreateReviewRequest.java
> +public record CreateReviewRequest(Integer ratings, String content) {
```suggestion
public record CreateReviewRequest(
Integer ratings,
 String content
 ) {
```

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/controller/review/ReviewControllerTest.java
> +        review.setUpdatedAt(LocalDateTime.of(2023, 8, 11, 23, 34, 8));
set Update라는 메서드를 왜 만드시고 사용하신건가요?

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/fixture/review/ReviewFixture.java
> +public class ReviewFixture {
개행 확인해주세요 그리고 전반적으로 코드 포맷팅이 안된거 같아용

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +class ReviewServiceTest extends IntegrationTest {
왜 통합테스트로 하신거죠?

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +class ReviewServiceTest extends IntegrationTest {
저희 서비스 테스트는 다른 이유가 없다면 단위 테스트를 하기로 정한 것 같아서요

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +        CreateReviewRequest request = new CreateReviewRequest(4, "이상은 인간에 실로 만천하의 아니다. 대중을 피가 이 보는 심장은 꽃이 역사를 일월과 만천하의 봄바람이다. 피고, 기쁘며, 뼈 길지 속에서 이상이 싸인 황금시대다. 가진 같으며, 풀밭에 이것이다. 보내는 우는 산야에 인생을 부패를 뿐이다.
이게 글자가 100이 넘는지 안넘는지는 확실하지 않아보이는데 확실하게 코드로 표현한다던지 그럴 방법이 없을까요?

2023-08-10 01:35 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +                .hasMessage("리뷰 내용은 최대 200자 입니다");
최대 200자라는 메세지와 테스트 케이스의 이름은 안맞는것가타요

2023-08-10 01:37 UTC, drunkenhw commented on backend/src/docs/asciidoc/review.adoc
> +include::{snippets}/review-controller-test/find-reviews/response-fields.adoc[]
restdocs 문서는 이것 뿐이가요?

2023-08-11 02:06 UTC, kiarakim reviewed
감사합니다. 근데 이거 왜 pending? 아직 반영 다 안해서 아직은 안해주셔도 돼여

2023-08-11 02:06 UTC, kiarakim commented on backend/src/docs/asciidoc/review.adoc
> +include::{snippets}/review-controller-test/find-reviews/response-fields.adoc[]
CRUD 다 있어야겠죠?네..

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +        return ResponseEntity.noContent().build();
보내줄게 없어서요. ok가 좋으려나요

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +    @PostMapping("/api/reviews/{reviewId}")
아이고. 네 감사합니다

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +    public ResponseEntity<Void> updateReview(
patch가 좋겠죠 아무래도

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponse.java
> +public record ReviewResponse(Long reviewId,
중간에 바꾼걸 적용 못햇네요 빼겟습니다

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +import javax.persistence.*;
아니 이거 왜 설정 적용 안된는거이무ㅜㅜ

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +public class Review extends BaseEntity {
네

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +public class Review extends BaseEntity {
근데 왜 다른 도메인엔 없죠?

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    private long id;
잘못했습니다...

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    private String stationId;
그거 잘 몰라서요... JPA 5장 참고해서 다시 해볼겡ㅇㅇ여

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    private Long memberId;
몰라서요. 적용해볼게여

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    }
SqlDelete 좋네요

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +}
추가햇습니다. 예리하셔라

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/ReviewRepository.java
> +    Review findById(Long reviewId);
네에 감사합니다

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/exception/review/ReviewExceptionType.java
> +    INVALID_RATINGS_NOTNULL(Status.INVALID, 2001, "별점은 null이 될 수 없습니다"),
네에

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/exception/review/ReviewExceptionType.java
> +    UNAUTHORIZED_MEMBER(Status.UNAUTHORIZED, 2006, "리뷰 작성자와 수정자가 다릅니다");
했어요

2023-08-11 02:06 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +        List<Review> allByStationId = reviewRepository.findAllByStationId(stationId);
페이징을 했다고 생각했느데 다 갖고와서 부분만 리턴하는게 페이징이 아니었네요. 수정했습니다

2023-08-11 02:44 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +    private void validateRequest(CreateReviewRequest request) {
네 도메인에서 하도록 했습니다

2023-08-11 02:45 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +    @DeleteMapping("/api/reviews/{reviewId}")
넵

2023-08-11 02:50 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +        if (!review.getMemberId().equals(memberId)) {
네 좋은 것 같아요

2023-08-11 02:52 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +                .hasMessage("리뷰 내용은 null이 될 수 없습니다");
그렇네요. 감사합니다

2023-08-11 02:52 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/domain/review/ReviewRepositoryTest.java
> +        String stationId = "ME101010";
넵 감사합니다

2023-08-11 02:53 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    private Long memberId;
잘 몰라서 안했는데 적용했습니다!

2023-08-11 02:55 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +        return reviewsByPage(allByStationId, page);
```java
pageable = PageRequest.of(pageable.getPageNumber(), PAGE_ELEMENT_SIZE, Sort.by(Sort.Direction.DESC, "createdAt"));
        Page<Review> reviews = findPageReviews(stationId, pageable);
```

이런 식으로 바꾸봤는데 PAGE_ELEMENT_SIZE는 한 페이지에 나올 리뷰 개수, 즉 10개를 의미합니다.
그래서 조회할 때 쿼리파라미터로 받은 page에 맞춰서 최대 PAGE_ELEMENT_SIZE개를 가져옵니다

2023-08-11 02:57 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +    }
좋은 생각인 것ㄱ 같아요 . 적용했습니다

2023-08-11 02:57 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +        return review;
검증과 검증이 아닌 것들을 나누려고 하다 보니 그렇게 됐습니다. 로직이 바껴서 불편함도 사라지셨을겁니다

2023-08-11 02:59 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/dto/CreateReviewRequest.java
> +public record CreateReviewRequest(Integer ratings, String content) {
두개여도 줄바꿈을 하는군요

2023-08-11 03:01 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/controller/review/ReviewControllerTest.java
> +        review.setUpdatedAt(LocalDateTime.of(2023, 8, 11, 23, 34, 8));
The documented type of the field 'reviews[].latestUpdateDate' is String but the actual type is Null
위와 같은 에러가 났는데 review의 최근 수정일에 값이 들어가있지 않아서 직접 넣어줬습니다

2023-08-11 03:03 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +class ReviewServiceTest extends IntegrationTest {
지우고 fake레포지토리 사용했습니다.

2023-08-11 09:49 UTC, closed without merging