feat: 데이터 암호화 기능 추가
woowacourse-teams/2023-car-ffeine pull request #43
Opened 2023-07-06 12:31 UTC by kiarakim

## 📄 Summary
>  jasypt를 사용한 데이터 암호화 기능 추가

## 🙋🏻 More
>

2023-07-06 12:53 UTC, drunkenhw requested changes
모르는 부분위주로 리뷰 남겼습니다~

2023-07-06 12:53 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
> +    String encryptKey;
얘는 왜 접근제어자가 없나요?

2023-07-06 12:53 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
> +            encryptKey = lines.get(0);
`get(0)`보다 상수화하는게 어때요?

2023-07-06 12:53 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
> +        }
예외는 나중에 처리할건가요?

2023-07-06 13:09 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
> +    String encryptKey;
붙여주었습니다~
추가로 
```java
List<String> lines;
```
는 클래스에서 한번밖에 사용하지 않아 지역변수로 넣었습니다!

2023-07-06 13:11 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
> +            encryptKey = lines.get(0);
예리하시네요👍 KEY_LINE으로 매직넘버 제거했습니다

2023-07-06 13:11 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
> +        }
네 팀원들과 상의 후 처리 예정입니다!

2023-07-06 13:18 UTC, drunkenhw reviewed
수정하신거 잘 봤습니다 제 생각 남겨봤습니다~

2023-07-06 13:18 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
> +    private final String encryptKey;
상수와 필드는 개행해주세용

2023-07-06 13:18 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
> +            String path = getClass().getClassLoader().getResource("encryptKey.txt").getPath();
이것도 `@Value("${jasypt.encryptor.service_key}")`이런식으로 `encryptKey.txt`를 다른 곳에서 관리하는 방법은 어떨까요?

2023-07-07 00:43 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
> +            String path = getClass().getClassLoader().getResource("encryptKey.txt").getPath();
근데 생각해보니 굳이 encrptKey를 파일로 가지고 있어야할까요? 
환경 변수로 세팅해놓는게 편하지 않을까요??
배포를 했을 때 `ec2 환경에 파일을 넣기 vs 환경 변수 설정하기`

2023-07-07 03:36 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
> +            String path = getClass().getClassLoader().getResource("encryptKey.txt").getPath();
'.' 컨벤션 적용해주세요~

2023-07-07 03:39 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/config/JasyptConfig.java
> +    public StringEncryptor stringEncryptor() {
메서드 명은 동사로 시작하도록 바꿔주세요~
예를들면 `encryptString()` 요런 느낌? 키아라가 적절하게 바꿔주세요!

2023-07-07 03:39 UTC, sosow0212 commented on backend/src/main/resources/application.yml
> +    url: ENC(6/ZOojQlvtQdd5CBHi/Yu9wLLwHm4ITUTWTt4xkN/4gEVW/siBnE3K9/qlDJvma0tQNwJhDbFpUqVg4RjEQBDJB2x5bGbGXpm3vWpDaMowHIdQ0bhMu2JR0RLawtlFC4ngBubRZOfd/+xx85JS/Y/0BStoh9nJ/jB+Ch4lVAEHk=)
잘 적용하셨네요 굿굿굿👍👍

2023-07-07 03:40 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/service/ScrapperService.java
> +    private String SERVICE_KEY;
서비스 키도 잘 숨겨주셨네요~

2023-07-07 03:41 UTC, sosow0212 requested changes
리뷰 확인하고, 몇 부분만 고쳐주세요~ 작업하시느라 수고 많으셨습니다!

2023-07-09 03:34 UTC, be-student approved these changes
Docker compose 하나 제외하고는 괜찮은 것 같아요
이 부분만 바꿔주시면 완벽할 것 같아요
고생 많으셨어요

2023-07-09 03:34 UTC, be-student commented on docker-compose.yml
> +      MYSQL_DATABASE: ENC(Fw2m3tTRDhkVAlUe7CBjFQ==)
Docker compose 를 실행하는 환경은 로컬이니까 로컬 데이터는 암호화 안 해도 괜찮을 거 같아요

암호화 해도 잘 실행이 되나요?

2023-07-09 09:29 UTC, sosow0212 approved these changes
잘 변경해주셔서 여기서 어프루브 할게요~
작업하시느라 수고하셨습니다 👍

2023-07-09 09:31 UTC, drunkenhw approved these changes
수고하셨습니다

2023-07-10 05:46 UTC, merged