feat: 필터 추가 및 개인화 메뉴를 만든다
woowacourse-teams/2023-car-ffeine pull request #430
Opened 2023-08-10 07:18 UTC by sosow0212

## 📄 Summary
1. 필터 추가 기능을 만들었습니다. 기존 프론트엔드 서버에서 상수로 관리하던 필터를 이제는 관리자 페이지를 통해서 관리할 수 있습니다.
2. 개인화 메뉴를 만들어습니다.
- 모든 유저는 자신의 차량을 등록할 수 있습니다.
- 모든 유저는 자신이 선호하는 필터셋을 정할 수 있습니다. 필터 테이블을 각각 나눈 이유는 필터 값의 타입이 다른 경우도 있고, 관리하는 값의 개수가 달라서 따로 만들어주었습니다.

## 🕰️ Actual Time of Completion
>

## 🙋🏻 More
>

2023-08-10 08:02 UTC, drunkenhw requested changes
제이 수고하셨습니다. 몇가지 질문이 있는데요.
1. 혹시 이렇게 company, capacity, connector type 으로 테이블을 정규화하셔서 구현하신 이유가 있을까요?
2. 혹시 그렇다면 Station의 company와 Charger의 capacity, connectorType도 값이 아닌 해당 테이블을 가지는 것이 좋지 않을까요?
3. repository의 테스트는 작성안하신 이유가 있을까요?
4. 지금 다 구현하셨겠지만 혹시 좀 더 쉽게 하시는 것은 어떨까요..?
```mermaid 
erDiagram
    Member ||--o{ MEMBER-FILTER : places
    Member {
        string id
        string name
        string email
    }
    MEMBER-FILTER
    MEMBER-FILTER {
        int id
        int filterId
        int memberId
    }
    FILTER ||--o{ MEMBER-FILTER : places
FILTER{
        int id
        string filterType
        string name
    }
```
고생하셨습니다 :+1:

2023-08-10 08:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/filter/service/FilterService.java
> +package com.carffeine.carffeine.filter.service;
filter의 service 패키지와 controller 패키지가 양방향으로 의존하고 있어서 수정해주셨으면 좋겠습니다

2023-08-10 08:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/filter/domain/companyName/CompanyName.java
> +public class CompanyName {
CompanyName이라고 하신 이유가 있으신가요?
그냥 Company로 해도 괜찮을 것 같아서요

2023-08-10 08:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/filter/domain/connectorType/ConnectorType.java
> +
key와 value는 무엇인가요

2023-08-10 08:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/filter/domain/companyName/CompanyName.java
> +
key와 name은 무엇인가요

2023-08-10 08:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/filter/domain/companyName/CompanyName.java
> +}
builder 패턴을 사용하지 않고 이렇게 생성하신 이유가 있으신가요?

2023-08-10 08:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/member/controller/dto/CarPersonalizationRequest.java
> +public record CarPersonalizationRequest(String name,
괄호하고 개행 부턱드려요

2023-08-10 08:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/member/controller/dto/MemberCustomFilterRequest.java
> +public record MemberCustomFilterRequest(List<CompanyNameRequest> companyNames,
ditto

2023-08-10 08:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/member/controller/MemberController.java
> +public class MemberController {
아래 메서드들은 MemberController에서 한다는 것이 저한텐 조금 이상하네요
prefix가 /members 인데 post 요청을하면 멤버가 등록이 되어야할 것 같고 get 요청을 하면 멤버 전체 조회가 될 것 같은데 그런게 아닌 것 같네요 
그래서 해당 메서드들은 filter 패키지로 이동하는 것이 어떨까라는 의견입니다.

2023-08-10 08:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/member/service/MemberService.java
> +package com.carffeine.carffeine.member.service;
해당 클래스도 양방향 의존 같아요

2023-08-10 08:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/member/service/MemberService.java
> +    public Personalization uploadCarPersonalization(Long memberId, CarPersonalizationRequest request) {
차를 등록하면 filter가 적용되는 로직은 없을까요..?

2023-08-10 08:43 UTC, be-student requested changes
pr 메시지를 조금 더 자세하게 적어주시면 더 잘 이해가 될 것 같아요 😢 
필터를 서버로 옮기기로 한 이유가 뭔지, 
박스터도 말을 했지만, Table 을 저렇게 설계하게 된 이유는 뭔지
같은 부분들이요

2023-08-10 08:43 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/filter/domain/capacity/Capacity.java
> +}
이 Capacity 는 왜 table 이 된 것인가요?

2023-08-10 08:43 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/filter/service/FilterService.java
> +}
메서드 순서를 맞춰주세요

2023-08-10 08:43 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/member/domain/filter/MemberCompanyNameFilter.java
> +    @ManyToOne(fetch = FetchType.LAZY)
ManyToOne 에서 다 lazy 로 달아둔 이유는 뭔가요?

2023-08-10 12:59 UTC, sosow0212 commented
@be-student 
> pr 메시지를 조금 더 자세하게 적어주시면 더 잘 이해가 될 것 같아요 😢 필터를 서버로 옮기기로 한 이유가 뭔지, 박스터도 말을 했지만, Table 을 저렇게 설계하게 된 이유는 뭔지 같은 부분들이요
> 
> 조금 작은 단위로 pr 이 올라오면 더 좋을 것 같아요

ㅠㅠ 그러게요 제가 개발하다보니 익숙해서 작업양에 비해서 짧게 메시지를 남기게 됐습니다. 이 부분은 앞으로 신경쓸게요
위와 같이 테이블을 설계한 이유는 기존에 작성했고 추가적으로 필터 추가를 왜 하게 됐는지 남겼습니다!

---

@drunkenhw 
> 제이 수고하셨습니다. 몇가지 질문이 있는데요.
> 1. 혹시 이렇게 company, capacity, connector type 으로 테이블을 정규화하셔서 구현하신 이유가 있을까요?
> 2. 혹시 그렇다면 Station의 company와 Charger의 capacity, connectorType도 값이 아닌 해당 테이블을 가지는 것이 좋지 않을까요?
> 3. repository의 테스트는 작성안하신 이유가 있을까요?
> 4. 지금 다 구현하셨겠지만 혹시 좀 더 쉽게 하시는 것은 어떨까요..?
> 아래 처럼 filter Type에 Company, Capacity, Connector... 이런게 들어오도록..?

1. 제안해주신 방법을 처음에 떠올렸습니다. 그래서 처음에 ENUM으로 필터의 종류를 관리하는 방식으로 만드려고 했으나 문제점이 있었습니다. 
- `충전소명`같은 경우 프론트엔트 측에서는 key와 value로 받아야한다. (동일한 광주시가 있을 수 있는데, 제공된 key로 구별할 수 있습니다.) 하지만 `충전속도`같은 경우에는 BigDecimal 값만 있으므로 이 경우 저장할 시에 value가 null이 됩니다. 또한 null이 들어가도 허용된다고 가정해도 데이터별로 타입이 다릅니다. key Column에는 BigDecimal과 String타입 둘 다 들어올 수 있습니다. (이 부분은 String으로 만들 수 있지만, 문제가 있을 수 있다고 생각합니다!)

2. 현재 테이블에서 외래키로 해당 테이블의 주소값을 참조하자는 말씀이신거죠? 이 부분은 동의합니다! 많은 부분을 고쳐야하기 때문에 추후 해당 작업을 마치고 issue 등록해서 진행하겠습니다.

3. ㅠㅠ 꼼꼼한 테스트 진행하겠습니다.

4. 제가 만들었지만, 복잡하다고 생각합니다. 더 쉽게하고 싶지만 제가 1번에서 답변한 것처럼 몇 가지 제약들이 있어서 일단 해당 구조로 진행했습니다. 지금 구조라면 필터가 추가된다면 무수히 많은 코드들이 추가되어야하고 리팩토링의 대상이 된다는 문제점을 인지하고 있습니다. 이런 경험이 많지 않아서 금요일에 팀원들 의견을 들어보고 리팩토링을 진행하도록 하겠습니다!

2023-08-10 13:25 UTC, kiarakim approved these changes
와우.. 수고하셨어요. 저는 어프룹 할게요

2023-08-10 13:25 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/filter/domain/capacity/Capacity.java
> +@Table(name = "capacity")
Capacity가 엔티티가 되었네여. 
근데 클래스 이름을 Capacity로 해도 db에선 자동으로 capacity가 되지 않나요? 와이 명세?

2023-08-10 13:25 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/member/controller/MemberController.java
> +    @PostMapping
이 Post는 /api/members에 바로 등록하네요. 헷갈려서 그러는데 이 요청은 필터가 적용되기 전 최초의 요청인가요?

2023-08-11 01:04 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/filter/domain/connectorType/ConnectorType.java
> +
ConnectorType으로 예시를 들면 (key = "DC_COMBO", value = "DC 콤보") 입니다
네이밍이 헷갈려서 수정하도록 하겠습니다~

2023-08-13 08:37 UTC, closed without merging