feat: 위도, 경도를 바탕으로 간단 정보 조회 API를 구현한다
woowacourse-teams/2023-car-ffeine pull request #44
Opened 2023-07-06 15:15 UTC by drunkenhw

## 📄 Summary
> 구현에 특이점은 fake repository를 사용하여 service를 테스트 했다는 점과 
네이밍에 재주가 없어 네이밍이 맘에 들지 않는다는 점,
rest docs를 잘 몰라 제대로 사용한건지 잘 모르겠네요.

## 🙋🏻 More
> 꼼꼼히 봐주세요
그리고 현재 조회 시 발생하는 쿼리가 많아 리팩터링이 필요할 것 같습니다.
처음에는 `해당 범위 내의 충전소 모두 조회 쿼리 1번 -> 조회한 충전소에 있는 충전기를 조회 N번 -> 충전기들의 상태를 조회하는 쿼리 N번` 발생하여 `@EntityGraph` 어노테이션으로 아래와 같이 줄였습니다.
현재는 `해당 범위 내의 충전소 모두 조회 쿼리 1번 -> 조회한 충전소에 있는 충전기들의 상태를 조회하는 쿼리 N번`이 발생합니다.

close #28

2023-07-07 00:56 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargerState.java
> +    public static ChargerState of(int input) {
인자가 1개이니 from으로 바꾸는 건 어떨까요?

2023-07-07 00:57 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargerState.java
> +                .filter(it -> it.value == input)
it이라는 네이밍보다는 조금 더 명확한 네이밍으로 바꾸는 건 어떨까요?

2023-07-07 01:01 UTC, be-student requested changes
from 을 잘 지켜주세요 😢

2023-07-07 01:01 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargerState.java
> +    public static ChargerState of(int input) {
from 으로 바꿔주세요 😢

2023-07-07 01:01 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/controller/ChargerStationController.java
> +        ChargeStationsSimpleResponse chargerStationsSimpleResponse = ChargeStationsSimpleResponse.of(chargeStations);
from 으로 바꿔주세요 😢

2023-07-07 01:01 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/dto/ChargeStationsSimpleResponse.java
> +                                )).toList(),
이 부분을 메서드로 분리해주시면 어떨까요?

2023-07-07 01:35 UTC, sosow0212 requested changes
구현 잘 해주셨네요! 리뷰 확인해보고 고쳐주세요~
수고하셨습니다!!

2023-07-07 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargerState.java
> +public enum ChargerState {
컨벤션에 맞게 개행 한 칸 추가해주세요~

2023-07-07 01:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/dto/ChargeStationsSimpleResponse.java
> +                                .map(it2 -> new ChargerSimpleResponse(
이 부분도 it2라는 네이밍보다는 조금 더 이해하기 좋은 걸로 바꿔주세요~

2023-07-07 01:35 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/controller/ChargerStationControllerTest.java
> +                .andDo(customDocument("findChargeStation"));
`RestDocs`에서 , Request와 Response 필드도 추가해서 문서 조각 + 값 검증 해주세요.

2023-07-07 01:35 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/fixture/ChargerFixture.java
> +    public static final Charger 선릉역_충전기_1번_사용가능 = Charger.builder()
재사용 가능한 Fixture 👍👍

2023-07-07 01:35 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/service/ChargerStationServiceTest.java
> +        chargeStationRepository = new FakeChargeStationRepository();
Fake 좋네요! 근데 `findAllBy~` 메서드가 실제로 같은 동작을 한다고 알 수 있을까요?
테스트가 성공은 하지만 실제 환경에서는 다르게 나올 수도 있을 것 같다고 생각하는데 이에 대해서는 어떻게 생각하시나요?

2023-07-09 05:58 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargerState.java
> +    public static ChargerState of(int input) {
바꿨습니다

2023-07-09 05:59 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargerState.java
> +                .filter(it -> it.value == input)
코틀린에서 stream 을 사용할 때 `it`이기도 하고  또 길어지는 것 보다 그냥 짧은게 좋아서 저는 이렇게 사용하는데 이 부분도 다 같이 정해보죠!
@be-student @kiarakim

2023-07-09 06:00 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/dto/ChargeStationsSimpleResponse.java
> +                                )).toList(),
분리했어요

2023-07-09 06:00 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/controller/ChargerStationControllerTest.java
> +                .andDo(customDocument("findChargeStation"));
적용했습니다 엄청 길어지네요..

2023-07-09 06:02 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/service/ChargerStationServiceTest.java
> +        chargeStationRepository = new FakeChargeStationRepository();
그런 문제가 생길 수는 있을 것 같습니다. 하지만 fake 객체 구현을 잘하면 문제가 되지 않을 거라 생각합니다. 서로 리뷰를 꼼꼼히 해주면 그런 문제가 생기지 않을 수 있을 것 같아서요

2023-07-09 06:09 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargerState.java
> +                .filter(it -> it.value == input)
저도 it 좋아요

2023-07-09 06:30 UTC, be-student requested changes
정말 잘 짜서 별로 리뷰 달만한게 없네요
고생 많으셨어요

2023-07-09 06:30 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/common/BaseException.java
> +    @Override
이 부분은 없는게 좋을 거 같아요
우리의 메시지가 필요하다면 이 부분 대신
생서자에서 super(exceptionType.getMessage())를 호출해서 진짜 메시지를 넣어주는 방향이 좋을 것 같아요

2023-07-09 06:30 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargeStation.java
> +    private Longitude longitude;
Embedded 보다, Longitude 와Latitude 쪽에 가서 Embeddable 을 붙히는 방향은 어떤가요?
이미 붙어있으니 embedded 를 생략하죠

2023-07-09 06:30 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/domain/Latitude.java
> +    public Latitude minLatitude(BigDecimal deltaX) {
네이밍이 min, max 라고 하면 koreaMin 을 줄 것 같아요

2023-07-09 06:30 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/domain/Longitude.java
> +    protected Longitude(BigDecimal value) {
Protected 일 필요 없어보여요

2023-07-09 06:39 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/common/BaseException.java
> +    @Override
good idea!

2023-07-09 06:42 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargeStation.java
> +    private Longitude longitude;
이런 방식도 되는지 몰랐네요 책에선 양쪽다 붙이라고했는데..

2023-07-09 06:42 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/Latitude.java
> +    public Latitude minLatitude(BigDecimal deltaX) {
그럴수도 있겠네요 `minLatitudeByDelta()`라고 수정했습니다

2023-07-09 06:42 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/Longitude.java
> +    protected Longitude(BigDecimal value) {
네

2023-07-09 06:49 UTC, be-student approved these changes
하나남겼는데 저 부분은 팀과 상의해야 할 것 같네요
@sosow0212 @kiarakim

2023-07-09 06:49 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/dto/ChargeStationInfoRequest.java
Dto 들의 패키지를 사용하는 위치를 고려해서 넣어두면 어떨까요?
서비스에서 사용하는 dto 는 서비스 패키지 안에
Controller 에서만 사용되는 dto 는 컨트롤러 패키지에

2023-07-09 09:19 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/Charger.java
> +    private BigDecimal price;
원시값 포장으로 잘 바꿔주셨네요 👍

2023-07-09 09:20 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/ChargerState.java
> +
리뷰가 남겨지지 않아서 여기다가 남길게요~
of 메서드를 from으로 바꿔주시고, stream에 it을 state와 같은 네이밍으로 변경해주면 더 좋을 것 같아요. 바꿔주시고 나중에 머지해주세요!

2023-07-09 09:21 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/Latitude.java
> +    private static final BigDecimal KOREA_MIN_LATITUDE = BigDecimal.valueOf(33);
범위 지정해준거 아주 좋습니다!

2023-07-09 09:22 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/Latitude.java
> +    public Latitude minLatitudeByDelta(BigDecimal delta) {
메서드 명은 동사로 시작할 수 있도록 리팩토링 해주세요

2023-07-09 09:27 UTC, sosow0212 approved these changes
몇 가지 네이밍만 변경해주세요~
작업하시느라 수고하셨습니다 어프루브 하고 갈게요!
통합테스트를 하면 좋겠지만, 서비스 특성상 현재 작업하신 부분은 힘든 것 같은데 이 부분을 더 신뢰성 있게 테스트 할 방법을 같이 찾아봐야할 것 같아요.
Rest Docs도 처음 사용해서 어려우셨을텐데 잘 사용해주셨네요 👍👍

2023-07-09 09:28 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/dto/ChargeStationInfoRequest.java
저도 이렇게 사용 레이어별로 정리하는 거 찬성합니다

2023-07-10 05:57 UTC, kiarakim reviewed
잘 작성해주셔서 제 리뷰는 상수화밖에 없네여. 수고하셨습니다~👍

2023-07-10 05:57 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/domain/Latitude.java
> +    private static final BigDecimal KOREA_MAX_LATITUDE = BigDecimal.valueOf(39);
33, 39 와 같은 숫자들은 상수화 하면 좋을 것 같아요~

2023-07-10 05:57 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/domain/Latitude.java
> +        if (value.compareTo(KOREA_MIN_LATITUDE) < 0 || value.compareTo(KOREA_MAX_LATITUDE) > 0) {
가능하다면 여기도 상수화!

2023-07-10 05:57 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/domain/LatitudeTest.java
> +    }
이렇게 테스트가 한번에 끝나는 경우엔 주석을 따로 달지 않나요?
// when & then 
처럼?

2023-07-10 05:57 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/fake/FakeChargeStationRepository.java
> +                .filter(it -> it.getLongitude().getValue().compareTo(minLongitude.getValue()) >= 0 && it.getLongitude().getValue().compareTo(maxLongitude.getValue()) <= 0)
상수화..?

2023-07-10 08:50 UTC, kiarakim approved these changes

2023-07-10 08:50 UTC, merged