feat: 리뷰 댓글 CRUD 기능을 구현한다
woowacourse-teams/2023-car-ffeine pull request #450
Opened 2023-08-11 09:54 UTC by kiarakim

## 📄 Summary
>  feat: 리뷰 댓글 CRUD 기능을 구현한다

## 🕰️ Actual Time of Completion
>

## 🙋🏻 More
>

2023-08-11 09:56 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +
이건 뺄게요ㅋㅋㅋ

2023-08-11 10:16 UTC, drunkenhw requested changes
수고하셨습니다 리뷰 몇개 달았습니다~

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/auth/controller/AuthFilter.java
> +            sendUnauthorizedError(response, "유효하지 않은 토큰입니다");
왜 필요한거죠? try catch

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/common/domain/BaseEntity.java
> +    @Setter
setter 왜 필요하죠?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +    @PostMapping("/stations/{stationId}/review")
reviews 로 고쳐주세요

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +    }
상태코드를 ok와 no content로 나뉘는 기준이 있을까요?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponse.java
> +        boolean isDeleted) {
괄호하나 개행해주세요

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponses.java
> +        int nextPage) {
ditto

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponses.java
> +        return new ReviewResponses(reviewResponses, nextPage);
dto에 로직이 들어가는 것은 저한테 조금 이상하네요 그리고 어떤 로직인지 이해하기 어려운데 어떻게 분리할 방법이 없을까요? 혹은 Page가 제공하는 다른 메서드를 찾아보시는 것은 어떠한가요

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    }
member id로 비교하는 이유가 뭐에요?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    }
이거 필요할까요?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +                .orElseThrow(() -> new MemberException(NOT_FOUND));
orElseThrow 가 반복되니 읽기 힘들어지는데 혹시 메서드로 분리하는 것은 어떤가요

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +                .isDeleted(false)
값을 안넣어도  default로 false일텐데 제거하는 것이 가독성이 좋지 않을까요?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    private boolean isUpdated;
이 필드가 필요할까요?
createdAt 과 updatedAt을 비교해서 update 됐는지 확인할 수 있지 않을까요?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +        Review review = reviewRepository.findById(reviewId).get();
get?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +    }
현재  `findAllReviews`만 사용하고 있어보이는데 PageRequest를 직접 만들어주는 이유가 무엇인가요?
`@PageDefault`였나 사용하면 이럴 필요가 없을 것 같아서요 그리고 Sort를 createdAt 기준으로 하는 이유가 무엇인가요? id로 정렬하는 것이 좀 더 성능상 이점이 있을 것 같아서요. 

그리고 마지막으로 무한스크롤과 비슷한 기능을 구현하려한다면
https://jojoldu.tistory.com/528
https://drunkenhw.github.io/java/oom/
이 글들을 참고하셔서 다른 방법으로 하시는 것은 어떤가요?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/domain/review/ReviewTest.java
> +        String content201 = "방황하여도, 용감하고 품고 뿐이다. 이는 불어 인생을 가지에 위하여서, 운다. 바이며, 날카로우나 가치를 작고 칼이다. 튼튼하며, 뭇 굳세게 열락의 그들은 쓸쓸하랴? 인도하겠다는 인생을 열매를 부패를 가지에 크고 붙잡아 설산에서 하는 말이다. 용기가 설레는 청춘은 보내는 온갖 같은 뿐이다. 그들에게 긴지
```suggestion
        String content201 = "*".repeat(201);
```
이런게 낫지 않을까요..?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReviewIntegrationTest.java
> +    Review 리뷰;
private이 아닌 이유는 뭘까요?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReviewIntegrationTest.java
> +    class 충전소에_댓글을_등록할_때 {
인수테스트 전반적으로 상태코드만 검증해도 될까요..?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReviewIntegrationTest.java
> +    String secret;
secret은 어디서 사용하죠?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +        assertThat(reviews1.reviews().size()).isEqualTo(0);
```suggestion
        assertThat(reviews1.reviews()).hasSize(0);
```
로 깔끔하게 할 수 있답니다

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +        assertThat(reviews.getNumberOfElements()).isEqualTo(10);
10개만 보여지면 검증이 끝나는 것일까요? 앞에서 10개인지도 중요하지 않을까요?

2023-08-11 10:16 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +    private FakeMemberRepository fakeMemberRepository;
인터페이스로 해주세요 ㅜ

2023-08-11 10:26 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/auth/controller/AuthFilter.java
> +            sendUnauthorizedError(response, "유효하지 않은 토큰입니다");
이게 인수테스트에서 잘못된 토큰으로 들어올 경우를 잡아주지 못해서 추가했습니다.

2023-08-11 10:32 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/common/domain/BaseEntity.java
> +    @Setter
테스트 때문에 달았는데, 오옹.. 감사합니다👍

2023-08-11 10:39 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +    @PostMapping("/stations/{stationId}/review")
네에~

2023-08-11 10:40 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +    }
그건 없어요. ok로 통일할래요

2023-08-11 11:13 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponse.java
> +        boolean isDeleted) {
네에

2023-08-11 11:14 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponses.java
> +        int nextPage) {
네에

2023-08-11 11:45 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponses.java
> +        return new ReviewResponses(reviewResponses, nextPage);
오 수정하니 훨씬 깔끔해졌네요,.
Page에서 isLast() 기능이 있더라구요. 현재 페이지가 마지막 페이지인지 확인하는 메서드입니다.

2023-08-11 12:00 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    }
기존에 필드로 memberId를 갖고있을 때 memberId로 비교하던 로직을 안바꿨네요. member끼리 비교해는게 좋을 것 같네요.

2023-08-11 13:10 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    }
이거 jpa로 deleteById(Long reviewId) 메서드 만들어서 시도해봤는데 계속해서 500에러 떠서 해결하려고 하는데 도통 해결이 안되네여.. 조금 못생겨도 일단 이렇게 하려고요. 좋은 방법 있으면 알려주십셔ㅜ

2023-08-11 16:26 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReviewIntegrationTest.java
> +    class 충전소에_댓글을_등록할_때 {
안되나요?
잘 저장 됐는지를 확인하는 방법이 있네요

2023-08-11 16:27 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReviewIntegrationTest.java
> +    Review 리뷰;
붙일게요

2023-08-11 16:27 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/domain/review/ReviewTest.java
> +        String content201 = "방황하여도, 용감하고 품고 뿐이다. 이는 불어 인생을 가지에 위하여서, 운다. 바이며, 날카로우나 가치를 작고 칼이다. 튼튼하며, 뭇 굳세게 열락의 그들은 쓸쓸하랴? 인도하겠다는 인생을 열매를 부패를 가지에 크고 붙잡아 설산에서 하는 말이다. 용기가 설레는 청춘은 보내는 온갖 같은 뿐이다. 그들에게 긴지
네에

2023-08-11 16:29 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/integration/review/ReviewIntegrationTest.java
> +    String secret;
jwtProvider사용하려면 필요할줄알았는ㄴ데 못지웟네요. 아니 근데 어떻게 그렇게 예리하게 보는거지?

2023-08-11 16:34 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +        assertThat(reviews.getNumberOfElements()).isEqualTo(10);
현재 페이지에 있는 리뷰의 개수에 추가로 현재 페이지를 검증하는건 어떤가요?

2023-08-11 16:41 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +    private FakeMemberRepository fakeMemberRepository;
울지마세요. 고쳤어요.

2023-08-12 00:50 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +        Review review = reviewRepository.findById(reviewId).get();
ㅠㅠ orElseThrow,,,로 바꿨습니다

2023-08-12 05:40 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +    }
@PageDefault 적용했습니다.
알려주신 다른 방법은 fetch join을 사용하고 있던데 그 부분을 잘 모르고, 
한 충전소에 리뷰가 몇만건 등록될진 않을 것 같아서 우선은 이정도만 하겠습니다.

2023-08-12 05:42 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    private boolean isUpdated;
되긴 하죠..
근데 Review에서 ReviewResponse 만들어줄때마다 그 둘을 비교하는 것보다 필드로 한번에 갖고오는게 편해서요.

2023-08-12 05:42 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +                .isDeleted(false)
default가 false군요. 알아갑니다.

2023-08-12 05:51 UTC, sosow0212 requested changes
박스터가 리뷰를 잘해줬네요
몇 가지 남겨봤습니다~ 확인해주세요!

2023-08-12 05:51 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/ReviewController.java
> +        return ResponseEntity.ok().build();
생성인데 200 상태코드를 주신 이유가 있을까요?

2023-08-12 05:51 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/controller/review/dto/ReviewResponses.java
> +        } else nextPage++;
박스터와 마찬가지로 로직이 들어가는 부분이 dto에 오는게 이상합니다 ㅠㅠ
그리고 만약에 저렇게 사용하는 것이라면 else는 제거해주시고, if문 안에 로직은 메서드 분리로 어떤 의미인지 명시해주는게 좋아 보입니다!

2023-08-12 05:51 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +    public ReviewResponses findAllReviews(String stationId, Pageable pageable) {
여긴 @Transactional(readonly=true) 해주는 게 좋지 않을까요!

2023-08-12 05:51 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +    public Page<Review> findPageReviews(String stationId, Pageable pageable) {
여기도 마찬가지입니다~

2023-08-12 05:51 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +        Review review = reviewRepository.findById(reviewId).get();
여기도 get이면 예외가 발생할 수 있을 것 같아요~

2023-08-12 05:51 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +    void 리뷰를_수정할_수_있다() {
다른 유저가 리뷰를 수정하는 경우 예외 검증도 해주면 어떨까요?

2023-08-12 05:51 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/station/service/review/ReviewServiceTest.java
> +    void 리뷰를_삭제한다() {
여기도 마찬가지입니다!

2023-08-12 05:58 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/review/Review.java
> +    private boolean isUpdated;
그러면 필드가 추가돼서 관리 포인트가 늘어나는 부분에 대해서는 어떻게 생각하시나요?
편한건 좋은 것 같은데 그에 따른 관리 포인트가 늘어나는 단점이 생길 것 같아서요

2023-08-12 07:33 UTC, be-student approved these changes
고생 많으셨습니다 👍

2023-08-12 07:42 UTC, drunkenhw approved these changes
isUpdate 필드를 빼실 생각은 없으신가요?
그리고 양방향 의존만 해결해주세요

2023-08-12 07:42 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +import com.carffeine.carffeine.station.controller.review.dto.ReviewResponses;
controller와 양방향 의존인 것 같아요

2023-08-12 07:42 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/review/ReviewService.java
> +        return ReviewResponses.of(reviews, getNextPage(reviews));
response를 리턴하는 이유가 있을까요? 
controller에서 조합해도 되지 않을까요?

2023-08-12 07:42 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/helper/integration/AcceptanceTestFixture.java
> +    }
이런식으로 확인한다면 type마다 메서드를 추가해야할 것 같은데 다른 방법으로 비교하는 것은 어떤가요?

2023-08-12 07:44 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/helper/integration/AcceptanceTestFixture.java
> +    }
이 부분은 일단 넘어가셔도 좋습니다~ 이슈를 새로 만들어서 진행하죠

2023-08-12 07:50 UTC, sosow0212 approved these changes
수고하셨습니다👍

2023-08-12 11:47 UTC, merged

2023-08-12 14:53 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/helper/integration/AcceptanceTestFixture.java
> +    }
넵