refactor: MemberCar 찾지를 못하면 null을 반환한다
woowacourse-teams/2023-car-ffeine pull request #492
Opened 2023-08-14 14:48 UTC by sosow0212

## 📄 Summary
> 유저의 차량을 찾지 못하면 null을 보냅니다.
현재는 찾지 못하면 exception을 보내는데, null을 보내야 프론트에서 처리할 수 있습니다.

## 🕰️ Actual Time of Completion
> 10분

## 🙋🏻 More
> 

close #491

2023-08-14 14:55 UTC, drunkenhw requested changes

2023-08-14 14:55 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/member/service/MemberService.java
>      }
흠 완전 null이라도 괜찮은 이유 설명해주실 수 있나요? 제 생각에는 인증 로직이 잘못된 갓 같아서요

2023-08-14 14:59 UTC, drunkenhw approved these changes
빠른 버그 수정을 위해 approve하겠습니다

2023-08-14 15:07 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/member/service/MemberService.java
>      }
null로 갔을 때 프론트에서 판단할 수 있다고 그래서 member_car가 없다면 null로 보내기로 했습니다!

인증로직이 잘못된 건 무슨 의미일까요!

2023-08-14 15:09 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/member/service/MemberService.java
>      }
로그인 안한 회원도 쓸 수 있게끔 해야할 것 같아서요 ㅎ

2023-08-14 17:21 UTC, be-student approved these changes
고생 많으셨습니다 👍

2023-08-15 01:58 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/member/service/MemberService.java
>      }
아~ 그러네요 ㅎㅎ 이 부분도 고치고 머지하겠습니다!

2023-08-15 02:26 UTC, kiarakim approved these changes

2023-08-15 02:27 UTC, merged