refactor: Car API 조회 기능을 Querydsl로 리팩토링 진행한다
woowacourse-teams/2023-car-ffeine pull request #633
Opened 2023-08-31 08:53 UTC by sosow0212

## 📄 Summary
> Car API 조회 기능을 Querydsl로 리팩토링 진행한다

## 🕰️ Actual Time of Completion
> 1시간

## 🙋🏻 More
>

2023-08-31 11:12 UTC, drunkenhw requested changes
수고하셨습니다.
리뷰 몇개 남겼습니다.
그리고 filter 관련해서 내일 한번 얘기해보면 좋을 것 같아요

2023-08-31 11:12 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/car/controller/CarController.java
> +    private final FilterQueryService filterQueryService;
아 오늘 얘기하려던게 이제 생각났네요 지금 filter라는 도메인이 member 와 car 등 많은 패키지에서 순환 참조 되어 있는 것 같아 이 부분을 수정하는 것이 좋을 것 같아요. 한번 내일 얘기해보죠

2023-08-31 11:12 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/car/infrastructure/repository/CarQueryRepository.java
> +    }
```suggestion
    public List<CarResponse> findAllCars() {
        return jpaQueryFactory.select(
                                constructor(CarResponse.class,
                                        car.id,
                                        car.name,
                                        car.vintage
                                )
                        ).from(car)
                        .fetch();
                 }
```
이런식으로 반환하고 service에서 Carsresponse로 매핑하는 것이 좀 더 깔끔해보이는데 어떻게 생각하세요?

2023-08-31 11:12 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/car/infrastructure/repository/FilterResponse.java
> +package com.carffeine.carffeine.car.infrastructure.repository;
dto라는 패키지에 만드는 것은 어떤가요?

2023-08-31 11:12 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/filter/controller/dto/FiltersResponse.java
> +    }
dto를 받아서 domain으로 변경하고 그걸 다시 dto로 변환한다는 부분이 좀 이상한데요 깔끔하게 안될까요?

2023-08-31 11:12 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/car/infrastructure/repository/CarQueryRepositoryTest.java
> +            softly.assertThat(result.cars().get(1).name()).isEqualTo(car2.getName());
name이라는 필드만 비교하기보다 전체적으로 다 잘 나왔는지 비교하는 것이 좋지 않을까요?
저도 이런식으로 작성하다 에러가 생긴게 여러번이라서요

2023-08-31 11:12 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/car/service/CarQueryServiceTest.java
> +        assertThat(result.cars().get(0).name()).isEqualTo(car.getName());
ditto

2023-08-31 11:12 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/filter/infrastructure/repository/FilterQueryRepositoryTest.java
> +            softly.assertThat(result.get(0).name()).isEqualTo(carFilters.get(0).getFilter().getName());
여기도 좀 더 자세하게 검증 부탁드려요

2023-08-31 11:12 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/filter/infrastructure/repository/FilterQueryRepositoryTest.java
> +        List<CarFilter> carFilters = carFilterRepository.saveAll(List.of(new CarFilter(car, filters.get(0))));
save all을 사용하시는 이유가 무엇인가요?
직관적이지 않은 것 같아서요

2023-08-31 11:12 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/filter/service/FilterQueryServiceTest.java
> +        List<CarFilter> carFilters = carFilterRepository.saveAll(List.of(new CarFilter(car, filters.get(0))));
여기도요

2023-08-31 12:45 UTC, kiarakim approved these changes
수고하셨습니다!

2023-08-31 13:50 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/car/infrastructure/repository/CarQueryRepository.java
> +import com.carffeine.carffeine.car.controller.dto.CarsResponse;
dto 패키지 확인해주세용

2023-09-01 02:02 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/filter/infrastructure/repository/FilterQueryRepositoryTest.java
> +        List<CarFilter> carFilters = carFilterRepository.saveAll(List.of(new CarFilter(car, filters.get(0))));
저도 `save()`를 사용하는 것이 좋다고 생각하지만, 프로덕션 코드에서는 `saveAll()`로 모든 필터를 저장하는 구조로 되어있습니다.
테스트를 위해서 메서드를 추가하는 건 좋다고 생각하지 않아서 이 부분은 이대로 두겠습니다!

2023-09-01 04:11 UTC, sosow0212 commented
++ 0901

MemberFilter, CarFilter, Filter가 서로 의존해서

Filter관련은 모두 Filter API로 이전하였고, MemberCar와 같은 Car가 포함된 것은 모두 Car API로 이전하였습니다.
이로 인해 양방향 의존에서 단방향 의존으로 변경하였습니다.

2023-09-01 04:46 UTC, drunkenhw approved these changes
수고하셨습니다

2023-09-01 04:46 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/car/infrastructure/dto/FilterResponse.java
> +    }
생성자랑 같은 것 같아요

2023-09-01 04:46 UTC, kiarakim requested changes
수고하셨습니당~이 부분만 바꾸면 좋을 것 같아욥

2023-09-01 04:46 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/car/service/CarQueryServiceTest.java
> +            softly.assertThat(result.cars().get(0).vintage()).isEqualTo(car.getVintage());
이 부분은 usingRecursiveComparison()을 써서 비교하면 어떨까요?

2023-09-01 04:46 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/filter/infrastructure/repository/FilterQueryRepositoryTest.java
> +            softly.assertThat(result.get(0).filterType()).isEqualTo(filters.get(0).getFilterType());
여기도욥

2023-09-01 04:46 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/car/infrastructure/repository/CarQueryRepositoryTest.java
> +            softly.assertThat(result.get(1).vintage()).isEqualTo(car2.getVintage());
여기도 usingRecursive

2023-09-01 04:57 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/car/service/CarQueryServiceTest.java
> +            softly.assertThat(result.cars().get(0).vintage()).isEqualTo(car.getVintage());
해당 부분들은 dto라서 도메인과 `usingRecursiveComparison()`를 이용해서 비교할 수 없었습니다 ㅠ

2023-09-01 04:58 UTC, kiarakim approved these changes
수고하셨어요!

2023-09-01 05:12 UTC, merged