API 요청 key를 번갈아 사용하도록 설정한다
woowacourse-teams/2023-car-ffeine pull request #66
Opened 2023-07-12 05:03 UTC by kiarakim

## 📄 Summary
> 

## 🙋🏻 More
>

2023-07-12 05:20 UTC, be-student requested changes
gitignore 에 mysql 폴더를 추가하면 좋을 것 같아요

2023-07-12 05:20 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/service/ScrapperService.java
> +    private final Random random = new Random();
```suggestion
     private final ThreadLocalRandom threadLocalRandom= ThreadLocalRandom.current();
```

참고
https://velog.io/@sojukang/Random-%EB%8C%80%EC%8B%A0-ThreadLocalRandom%EC%9D%84-%EC%8D%A8%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

2023-07-12 05:20 UTC, be-student commented on backend/src/main/resources/application.yml
> +    password: ENC(0OkM1cOAS6M6p3TO8BJDMU3eBtGcB0/E)
이 부분도 localhost 로 직접 하드코딩해도 좋을 것 같아요

2023-07-12 10:42 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/service/ScrapperService.java
> +    private final Random random = new Random();
Random이 완전한 랜덤이 아니었다니 신기하네요.
새로운 기능 감사합니다~

2023-07-12 10:44 UTC, kiarakim commented on backend/src/main/resources/application.yml
> +    password: ENC(0OkM1cOAS6M6p3TO8BJDMU3eBtGcB0/E)
이부분을 하드코딩해도 되는지 몰랐네요. 감사합니다!

2023-07-13 05:59 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/domain/RandomKeySelector.java
> +    private final ThreadLocalRandom random = ThreadLocalRandom.current();
다른 클래스처럼 개행 한 칸 띄워주세요~

2023-07-13 06:00 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/service/ScrapperService.java
> +
필요하지 않은 개행은 없애주세요~

2023-07-13 06:02 UTC, sosow0212 requested changes
컨벤션 위주로 리뷰 남겨봤습니다~

2023-07-13 08:25 UTC, drunkenhw requested changes
궁금한거 위주로 리뷰남겼습니다~

2023-07-13 08:25 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/RandomKeySelector.java
> +    private final ThreadLocalRandom random = ThreadLocalRandom.current();
```suggestion
    private static final ThreadLocalRandom RANDOM = ThreadLocalRandom.current();
```
으로 하면 안되나요?

2023-07-13 08:25 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/service/ScrapperService.java
> +        String SERVICE_KEY = randomKeySelector.getRandomKey();
```suggestion
        String serviceKey = randomKeySelector.getRandomKey();
```
상수가 아니니깐 이게 맞지 않을까요?

2023-07-14 12:41 UTC, closed without merging