refactor: 혼잡도 조회 속도를 개선 및 리팩토링을 진행한다
woowacourse-teams/2023-car-ffeine pull request #679
Opened 2023-09-09 09:45 UTC by sosow0212

## 📄 Summary
> 혼잡도 조회 속도를 개선 및 리팩토링을 진행한다

## 문제 상황
기존 혼잡도 조회 시 slow query로 분석했을 때 최악의 경우 12분이 걸렸습니다.
수천만건의 데이터로 인해서 이런 결과가 나왔습니다.

이를 개선하기 위해서 먼저 7일에 해당하는 혼잡도를 조회하는 것이 아닌 요일별로 조회하도록 변경하였고, 파티셔닝과 인덱스를 설정해주었습니다.

## 속도적인 부분해서 해결
속도 측면에서는 이를 다음과 같이 개선했습니다.
- DB 파티셔닝 : [`day_of_week` : 요일]을 기준으로 파티셔닝
- 인덱스 설정 : DB 쿼리에 맞게 인덱스를 설정했습니다.

1. local에서 성능 테스트 한 경우 혼잡도 조회시 리팩토링 전 속도
- 약 511ms

2. local에서 성능 테스트 한 경우 혼잡도 조회시 리팩토링 후 속도
- 약 5ms (요일 별 조회)
- 만약 월~금 7일 조회시 약 35ms가 나옴을 기대할 수 있습니다.

3. 결과
- 511ms -> 5ms 로 102배 개선, 7일을 기준으로 했을 시 511ms -> 35ms 16배 개선
- 기존 서버에서 최악의 경우 slow_query를 통해서 확인한 결과 약 12분의 혼잡도 조회속도가 나왔습니다. 만약 해당 변경 사항으로 조회시에 최악의 경우 요일별 조회시 7초가 나올 수 있습니다.
파티셔닝 작업을 해서 실제로 이정도 나오진 않을 거라고 생각하지만, 추가적으로 개선을 더 하면 좋을 것 같습니다. (필요하다면 작업양이 많아서 해당 pr 이후에 진행하겠습니다.)

## 그 외 작업
- 기존 혼잡도 통계 API에서 테스트가 누락된 테스트를 채웠습니다.
- 도메인 인덱스 설정, flyway 변경사항 추가
- uri 변경
요일 별로 조회하도록 바뀌어서`혼잡도 조회 uri가 변경 되었습니다.`
`기존 uri` : /api/stations/{stationId}/statistics
`변경 후 uri` : /api/stations/{stationId}/statistics?dayOfWeek={Number: dayOfWeek}

## 🕰️ Actual Time of Completion
> 6시간

## 🙋🏻 More
> 자세한 작업 내용 및 진행 과정은 pr이 merge되고 팀 블로그에 기록하겠습니다.

2023-09-09 09:51 UTC, kiarakim approved these changes
오... 고생많으셨어요..👍 어프룹할게요

2023-09-09 10:02 UTC, drunkenhw requested changes
제이 수고하셨습니다
엄청 빠르시네요 
몇가지 코멘트 남겼습니다~

2023-09-09 10:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/congestion/CongestionController.java
> +                                                                       @RequestParam(required = false, defaultValue = MONDAY) int dayOfWeek) {
프론트에서 요일을 숫자로 받는 부분이 어색한데 혹시 프론트와 정의된 부분일까요?
왜냐면 그럴 일은 적겠지만  요일에 매핑되는 숫자가 변경이 된다면 프론트 코드와 백엔드 코드를 모두 수정해야하는 일이 생길 수 있어서
그냥 누구나 알기 쉬운 월요일이면 monday를 받고, tuesday를 받는 식으로 하는 것은 어떤가요

2023-09-09 10:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestion.java
> +@Table(name = "periodic_congestion", indexes = @Index(name = "idx_station_id_and_day_of_week", columnList = "station_id, day_of_week"))
이 인덱스는 필요한 것인가요? 파티셔닝을 하면서 station id와 요일로 프라이머리 키를 변경하지 않았나요?

2023-09-09 10:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestion.java
>      private DayOfWeek dayOfWeek;
이 부분도 primary key가 변경되었으니 어노테이션이 수정되어야 할 것 같아요

2023-09-09 10:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestionRepository.java
> +    List<PeriodicCongestion> findAllByStationIdAndDayOfWeek(String stationId, DayOfWeek dayOfWeek);
dto로 가져오지 않고 entity로 가져오는 이유는 무엇인가요? query dsl을 사용해서 dto로 필요한 값만 가져오는 것이 좋아보여서요

2023-09-09 10:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/congestion/CongestionService.java
>      }
이 검증 로직은 DayOfWeek 에 있는 것이 좋을 것 같은데 어떠신가요?

2023-09-09 10:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/congestion/CongestionService.java
> +        List<CongestionInfoResponse> standardSpeedResponse = calculateCongestions(congestions, chargers, false);
query dsl로 join해서 dto로 받아오면 쿼리 한번에 해결할 수 있을 것 같아요

2023-09-09 10:02 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/congestion/CongestionService.java
> +        List<CongestionInfoResponse> standardSpeedResponse = calculateCongestions(congestions, chargers, false);
그리고 지금 n+1 문제도 있어서요

2023-09-09 10:02 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/controller/congestion/CongestionControllerTest.java
> +                                fieldWithPath("congestion.standard[].ratio").type(JsonFieldType.NUMBER).description("혼잡도"),
description이 조금 이상한 것 같아요.
월요일 혼잡도를 요청했는데 화요일 혼잡도와 수요일 혼잡도 정보 이런 것들도 넘겨주나요?

2023-09-09 10:02 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/integration/congestion/CongestionIntegrationTest.java
> +    }
인수테스트 결과를 보면 -1 로만 반환된다는 것이 결과인데 다른 테스트도 추가하는 것은 어떠신가요

2023-09-09 10:02 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/station/service/congestion/CongestionServiceTest.java
> +        // when & then
상태 값이 있는 데이터는 테스트하지 않아도 될까요..?

2023-09-09 10:02 UTC, drunkenhw requested changes
제이 수고하셨습니다
엄청 빠르시네요 
몇가지 코멘트 남겼습니다~

2023-09-09 10:11 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestion.java
> +@Table(name = "periodic_congestion", indexes = @Index(name = "idx_station_id_and_day_of_week", columnList = "station_id, day_of_week"))
착각했네요 station id 와 day of week가 프라이머리 키 아니네요!

2023-09-09 10:11 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestion.java
> +@Table(name = "periodic_congestion", indexes = @Index(name = "idx_station_id_and_day_of_week", columnList = "station_id, day_of_week"))
그러면 flyway에 index 추가 sql도 넣어주셔야할 것 같아요

2023-09-11 04:35 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/domain/congestion/PeriodicCongestion.java
> +@Table(name = "periodic_congestion", indexes = @Index(name = "idx_station_id_and_day_of_week", columnList = "station_id, day_of_week"))
넵 실행 계획은 블로깅 얼른 정리해서 해당 pr 메시지에 추가해두도록 하겠습니다!

2023-09-11 08:08 UTC, drunkenhw approved these changes
수고하셨습니다

2023-09-11 08:08 UTC, merged