refactor: 충전소 마커를 덜 요청하도록 개선한다
woowacourse-teams/2023-car-ffeine pull request #700
Opened 2023-09-11 13:03 UTC by gabrielyoon7

## 📄 Summary
> 

 - 델타를 스크린보다 훨씬 크게 잡습니다.
 - 마지막 요청 영역을 기록합니다.
 - 마지막 요청 영역 내에서의 움직임이라면 재요청을 보내지 않습니다.

## 🕰️ Actual Time of Completion
>

## 🙋🏻 More
>

2023-09-11 13:04 UTC, kyw0716 approved these changes
좋습니다~

2023-09-11 13:42 UTC, feb-dain requested changes
휴대폰으로 보고 있어서 자세하게는 못 봤는데 리뷰 답변하고 있는 동안에 노트북으로 보겠습니다!

2023-09-11 13:42 UTC, feb-dain commented on frontend/src/hooks/tanstack-query/station-markers/useStationMarkers.ts
> +  return latitudeDelta === 0 && longitudeDelta === 0;
델타값이 0이면 맵이 로드가 된 건가요?

2023-09-11 13:42 UTC, feb-dain commented on frontend/src/hooks/tanstack-query/station-markers/useStationMarkers.ts
>    }
맵이 로드되면 throw Error를 던지나요?? 😮

2023-09-11 13:42 UTC, feb-dain commented on frontend/src/hooks/tanstack-query/station-markers/useStationMarkers.ts
> +  };
2 상수화 해주세요~

2023-09-11 13:42 UTC, feb-dain commented on frontend/src/constants/googleMaps.ts
> +export const INITIAL_ZOOM_SIZE = 16;
임시로 16으로 한 건가요? 아니면 픽스된 건가요?

2023-09-11 13:42 UTC, feb-dain commented on frontend/src/utils/google-maps/index.ts
> +}
1) 왜 중복되는 타입 `Pick` 안 썼나요??

2) Zoom이 들어가니까 Position이라는 이름이 애매하네요. 이게 화면에 보이는 맵 크기와 관련있는 거라면 `MapViewport`는 어떤가요?

2023-09-11 13:42 UTC, feb-dain commented on frontend/src/utils/google-maps/isCachedRegion.ts
> +};
이것들은 별도의 함수로 빼도 될 것 같아요
`isBoundsWithinCachedBounds`라는 이름의 함수로!

2023-09-12 01:16 UTC, gabrielyoon7 commented on frontend/src/constants/googleMaps.ts
> +export const INITIAL_ZOOM_SIZE = 16;
임시입니다

2023-09-12 01:18 UTC, gabrielyoon7 commented on frontend/src/hooks/tanstack-query/station-markers/useStationMarkers.ts
> +  return latitudeDelta === 0 && longitudeDelta === 0;
아뇨

2023-09-12 01:22 UTC, gabrielyoon7 commented on frontend/src/hooks/tanstack-query/station-markers/useStationMarkers.ts
>    }
헉

2023-09-12 01:22 UTC, gabrielyoon7 commented on frontend/src/hooks/tanstack-query/station-markers/useStationMarkers.ts
> +  };
네

2023-09-12 01:55 UTC, gabrielyoon7 commented on frontend/src/utils/google-maps/isCachedRegion.ts
> +};
네

2023-09-12 02:36 UTC, gabrielyoon7 commented
![image](https://github.com/woowacourse-teams/2023-car-ffeine/assets/69189073/90219aea-a06d-4d30-958e-637d75362797)

2023-09-12 02:38 UTC, feb-dain requested changes

2023-09-12 02:38 UTC, feb-dain commented on frontend/src/utils/google-maps/isCachedRegion.ts
> +export const isCachedRegion = (displayPosition: DisplayPosition) => {
위에 개행 좀 주세요

2023-09-12 02:38 UTC, feb-dain commented on frontend/src/utils/google-maps/isCachedRegion.ts
> +  return isBoundsWithinCachedBounds(cachedBounds, bounds);
여기도 개행 주세요~

2023-09-12 02:38 UTC, feb-dain commented on frontend/src/utils/google-maps/isCachedRegion.ts
> +  }
아래 위로 개행 주세요~

2023-09-12 02:40 UTC, feb-dain approved these changes
굿

2023-09-12 02:41 UTC, merged