refactor: 충전소 및 지역 검색 시 충전기가 아닌 충전소 기준으로 조회되도록 변경한다
woowacourse-teams/2023-car-ffeine pull request #701
Opened 2023-09-11 13:11 UTC by kiarakim

## 📄 Summary
> refactor: 충전소 및 지역 검색 시 충전기가 아닌 충전소 기준으로 조회되도록 변경한다

## 🕰️ Actual Time of Completion
> 20분

## 🙋🏻 More
>

2023-09-11 13:15 UTC, drunkenhw requested changes
해당 메서드를 호출했을 때 발생하는 쿼리도 같이 첨부해주면 좋을 것 같아요
그리고 테스트 코드도 추가하는 것이 좋을 것 같은데 어떻게 생각하시나요?

2023-09-11 13:15 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/controller/station/StationController.java
> +        StationsSearchResponse stationSearchResponse = stationQueryService.searchStations(query, scope, limit);
page 를 삭제한 이유는 무엇인가요?

2023-09-11 13:15 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/StationQueryRepository.java
> -                                        list(charger.type),
해당 위치에 코멘트를 남길 수가 없어서 여기다 남깁니다
groupby station id를 해주는 이유는 뭔가요? 그리고 transform으로 변환해주는 이유는 무엇인가요?

2023-09-12 01:04 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/controller/station/StationController.java
> +        StationsSearchResponse stationSearchResponse = stationQueryService.searchStations(query, scope, limit);
검색 결과를 페이지네이션 하지 않는다고 하네요.
야미와 누누가 처음 코드 작성할 떄 확장성을 위해 적어놓은 것 같아요.

2023-09-12 01:26 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/infrastructure/repository/station/StationQueryRepository.java
> -                                        list(charger.type),
단순히 필드만 제거하고 그 부분은 신경 못쓴 것 같네여. 변경했습니다!

2023-09-12 02:22 UTC, drunkenhw approved these changes
멋져요~~ 👍 🎉🌈🎆🎊🎇

2023-09-14 06:58 UTC, sosow0212 approved these changes
수고하셨습니다! 깔끔하게 잘 덜어내신 것 같아요

2023-09-14 06:58 UTC, merged