refactor: scrap 메서드를 리팩터링 한다
woowacourse-teams/2023-car-ffeine pull request #77
Opened 2023-07-13 05:42 UTC by be-student

## 📄 Summary
> 스크랩 메서드 리팩터링
시작시에, Application RUnner 를 활용해서 자동으로 실행할 수 있도록 작성했어
application.yml 을 테스트에서 사용할 수 있도록 테스트에도 yml 을 추가하였어요

## 🙋🏻 More
>

2023-07-13 05:52 UTC, drunkenhw requested changes
수고하셨습니다. 몇가지만 확인해주세요

2023-07-13 05:52 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/chargeStation/Longitude.java
> +//        }
주석 감사합니다~

2023-07-13 05:52 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/service/chargerStation/ScrapperService.java
> +        for (int i = 1; i <= 24; i++) {
24는 상수로 분리해주면 나중에 관리하기 편할 것 같아요

2023-07-13 05:52 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/infra/repository/ChargeStationRepositoryImplTest.java
> +}
왜 테스트가 없죠?

2023-07-13 05:52 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/chargeStation/ChargeStation.java
> +        }
필드에서 초기화 하는데 chargers가 null 일 경우가 있나요?

2023-07-13 05:52 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +public class RestTemplateChargeStationRequester implements ChargeStationRequester {
해당 클래스는 테스트할 수 없을까요?

2023-07-13 06:45 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/chargeStation/Longitude.java
> +//        }
굿

2023-07-13 06:46 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/service/chargerStation/ScrapperService.java
> +        for (int i = 1; i <= 24; i++) {
변경했습니다! 👍

2023-07-13 06:47 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/chargeStation/ChargeStation.java
> +        }
아하 제거했습니다

2023-07-13 08:20 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +        while (true) {
while 문으로 처리하셨네요 👍
페이지가 늘어나거나 줄어도 유동적으로 작동하겠네요

2023-07-13 08:21 UTC, be-student commented on backend/src/test/java/com/carffeine/carffeine/infra/repository/ChargeStationRepositoryImplTest.java
> +}
추가했어요~

2023-07-13 08:22 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +public class RestTemplateChargeStationRequester implements ChargeStationRequester {
포기했습니다 😢

2023-07-13 08:24 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/infra/repository/ChargeStationRepositoryImplTest.java
> +        // then
then 위에 개행 하나 추가해주세요~

2023-07-13 08:32 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/service/chargerStation/ScrapperService.java
> +            int page = i;
이 부분은 i를 넣으면 안 돼서 `int page = i;`로 할당해준 것 맞나요?

2023-07-13 08:34 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/infra/repository/ChargeStationRepositoryImplTest.java
> +    void 충전소가_잘_저장된다() {
`잘`이라는 용어는 빼는 것이 어떨까요🥲

2023-07-13 08:36 UTC, sosow0212 requested changes
scrap 코드가 깔끔해져서 보기 좋습니다~
몇 가지만 확인해주세요~

2023-07-13 08:37 UTC, be-student commented on backend/src/test/java/com/carffeine/carffeine/infra/repository/ChargeStationRepositoryImplTest.java
> +    void 충전소가_잘_저장된다() {
좋아요 👍

2023-07-13 08:38 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/service/chargerStation/ScrapperService.java
> +            int page = i;
네 맞아요
람다에서 effectively final 이거나,final 변수만 전달할 수 있어서, 할당을 했어야 했습니다

2023-07-13 08:38 UTC, be-student commented on backend/src/test/java/com/carffeine/carffeine/infra/repository/ChargeStationRepositoryImplTest.java
> +        // then
아하 감사합니다 👍

2023-07-13 08:38 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +        while (true) {
감사합니다 👍

2023-07-13 08:41 UTC, sosow0212 approved these changes
작업하느라 고생하셨습니다 🙇🏻‍♂️

2023-07-13 08:59 UTC, drunkenhw requested changes
고생하셨습니다 누누 열심히 모르는거 질문했어요

2023-07-13 08:59 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/infra/repository/ChargeStationRepositoryImplTest.java
> +        assertSoftly(softly -> {
`assertAll()`을 사용할 지 `assertSoftly()`를 사용할지 컨벤션을 정해봅시다..

2023-07-13 08:59 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +            Thread.sleep(1000);
요것도 1초를 상수로 빼놓으면 편하겠네요!

2023-07-13 08:59 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +        }
오 response entity로 감싸서 xml도 허용하게하는 센스 멋지네요

2023-07-13 08:59 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +    private ChargeStationRequest requestChargeStationRequestWithRetry(int pageNo) {
원래는 Optional을 반환했는데 null 로 바꾸신 이유가 있을까요?

2023-07-13 08:59 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +            } catch (Exception e) {
Exception이 터지는 이유가 InterruptedException말고 있나요?

2023-07-13 08:59 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +            throw new RuntimeException(exception);
얘는 왜 RuntimeException을 반환합니까

2023-07-13 09:34 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +            throw new RuntimeException(exception);
ExceptionHandler 에서 log error 를 찍기 위해서...?

2023-07-13 09:36 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +            } catch (Exception e) {
그렇네요 예외 자체가 안 터지겠네요 제거할게

2023-07-13 09:37 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +    private ChargeStationRequest requestChargeStationRequestWithRetry(int pageNo) {
성능상 안좋기도하고
도메인 내부에 null 이 돌아다니는 것도 아니라, Optional 을 쓸 이유가 없어보였어요
Optional 보다 null 이 더 코드가 깔끔해보여요

2023-07-13 09:37 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +        }
👍

2023-07-13 09:37 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +            Thread.sleep(1000);
감사합니다 👍

2023-07-13 09:37 UTC, be-student commented on backend/src/test/java/com/carffeine/carffeine/infra/repository/ChargeStationRepositoryImplTest.java
> +        assertSoftly(softly -> {
assertSoftly 쓰죠 👍

2023-07-13 10:32 UTC, drunkenhw commented on backend/src/test/java/com/carffeine/carffeine/infra/repository/ChargeStationRepositoryImplTest.java
> +        assertSoftly(softly -> {
근데 이 부분은 `usingRecursiveComparison()` 쓰면 깔끔해질 것 같은데.. 힘들지도 않고

2023-07-13 10:43 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/chargeStation/ChargeStationRequester.java
> +package com.carffeine.carffeine.domain.chargerStation.chargeStation;
이 클래스를 도메인 package에 두신 이유가 뭐에요

2023-07-13 11:16 UTC, kiarakim requested changes
많은 수정이 이뤄졌네요. 수고하셨어요~

2023-07-13 11:16 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +public class RestTemplateChargeStationRequester implements ChargeStationRequester {
Requester는 Request나 Service와 어떻게 다르죠?

2023-07-13 11:16 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/service/chargerStation/ScrapperService.java
> +            if (page != MAX_PAGE_SIZE && chargers.size() < 5000) {
매직넘버..!

2023-07-13 11:16 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/domain/chargerStation/charger/LongitudeTest.java
> +//    }
주석~

2023-07-14 00:16 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/chargeStation/ChargeStationRequester.java
> +package com.carffeine.carffeine.domain.chargerStation.chargeStation;
아니면 반환값이 dto가 아닌 'List<ChargeStation>' 이면 도메인 패키지에 있어도 괜찮을 것 같아요.

2023-07-14 01:32 UTC, be-student commented on backend/src/main/java/com/carffeine/carffeine/domain/chargerStation/chargeStation/ChargeStationRequester.java
> +package com.carffeine.carffeine.domain.chargerStation.chargeStation;
서비스 패키지로 바꾸었습니

2023-07-14 01:35 UTC, kiarakim approved these changes

2023-07-14 01:38 UTC, drunkenhw approved these changes
고생하셨습니다~

2023-07-14 01:38 UTC, merged