feat: 주요 도시에 대표 마커를 렌더링한다
woowacourse-teams/2023-car-ffeine pull request #817
Opened 2023-09-28 14:02 UTC by gabrielyoon7

## 📄 Summary

> 한반도 전체를 보여줄 때, 에러 메시지가 아닌 대표 마커를 렌더링하여 사용자에게 돌아가야(확대해야) 한다는 것을 알립니다.

![image](https://github.com/woowacourse-teams/2023-car-ffeine/assets/69189073/b763f92e-12dd-4408-967d-f89fccfaddfc)

그렇습니다.

이제는 한반도 전체를 볼 때, 주요 도시와 충전기 갯수를 보여줍니다.

다만, 중간(middle)단계는 아직 미구현이라 기존과 동일하게 뒀습니다.

도시 위치는 서버측에서 받아오므로 데이터를 잘 조절하면 될 것 같습니다.

폴더 구조도 일부 개선했으니 참고 바랍니다.

## 🕰️ Actual Time of Completion

> 3시간

## 🙋🏻 More

>

2023-09-29 13:15 UTC, feb-dain requested changes

2023-09-29 13:15 UTC, feb-dain commented on frontend/src/components/google-maps/map/CarFfeineListener.tsx
> +    console.log('zoomState: ' + zoom.state);
콘솔 안지워졌어요!
만약 필요한 콘솔이라면 주석 달아달라고 했는데 없으니 필요하지 않은 콘솔이라 판단하겠습니다!

2023-09-29 13:15 UTC, feb-dain commented on frontend/src/components/google-maps/marker/MarkersContainers.tsx
> +      {markerMode.state === 'low' && <MemoizedRegionCountMarkersContainer />}
이름 통일성 있게 이런 건 어떤가요?
```
 HighZoomMarkerContainer
 MiddleZoomMarkerContainer
 LowZoomMarkerContainer
```

2023-09-29 13:15 UTC, feb-dain commented on frontend/src/components/google-maps/marker/RegionCountMarkersContainer/components/RegionCountMarker.style.ts
> +`;
공통 컴포넌트 안 쓴 이유가 있을까요?

2023-09-29 13:15 UTC, feb-dain commented on frontend/src/components/google-maps/marker/RegionCountMarkersContainer/types/index.ts
> +}
그냥 `Region` 해도 될 것 같은데 RegionCount라고 한 이유가 있을까요?

2023-09-29 13:15 UTC, feb-dain commented on frontend/src/mocks/data.ts
> +export const regionCounts: RegionCount[] = [
여기도 왜 이름이 `regionCounts`인지 모르겠습니다. `regions` 아니면 `regionList`가 낫지 않을까요? `regionCount`는 지역 수가 몇 개 인지에 대한 정보만 있을 것 같아요.

2023-09-30 04:37 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/map/CarFfeineListener.tsx
> +    console.log('zoomState: ' + zoom.state);
[한참 전](https://github.com/woowacourse-teams/2023-car-ffeine/pull/817/commits/6de7d744678809c7aabe69f0368e5ee9375bd7a0)에 지웠는데 옛날 페이지를 본 것 같습니다.

2023-09-30 04:42 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/marker/MarkersContainers.tsx
> +      {markerMode.state === 'low' && <MemoizedRegionCountMarkersContainer />}
반영했습니다

2023-09-30 04:42 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/marker/RegionCountMarkersContainer/components/RegionCountMarker.style.ts
> +`;
초심을 잃었습니다

2023-09-30 05:36 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/marker/RegionCountMarkersContainer/components/RegionCountMarker.style.ts
> +`;
반영완료

2023-09-30 05:44 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/marker/RegionCountMarkersContainer/types/index.ts
> +}
모두 Region으로 변경했습니다.

2023-09-30 05:44 UTC, gabrielyoon7 commented on frontend/src/mocks/data.ts
> +export const regionCounts: RegionCount[] = [
모두 Region으로 변경했습니다.

2023-09-30 06:07 UTC, feb-dain approved these changes
Approve👍

디자인은 다음 이슈에서 좀 더 다듬어보면 좋을 것 같아요! 지금은 간격이 좀 가까워보여서
그리고 한글의 font weight가 너무 두꺼운 것 같기도 하고🤔 좀 더 가독성 좋게 만들 수 있을 것 같은데 숫자랑 한글 font size랑 weight이리저리 변경 한번 해보면 좋을 것 같아요 
색깔은 맘에 듭니다!

2023-09-30 06:09 UTC, feb-dain commented on frontend/src/components/google-maps/map/CarFfeineListener.tsx
> +    console.log('zoomState: ' + zoom.state);
ㅋㅋㅋㅋ리뷰가 pending 되었을 때 고쳤나봐여 이 리뷰는 좀 오래 전에 달아놨던 거라

2023-10-01 04:47 UTC, kyw0716 requested changes

2023-10-01 04:47 UTC, kyw0716 commented on frontend/src/components/google-maps/map/CarFfeineListener.tsx
> +      warningModalActions.openModal(<ZoomWarningModal />);
zoom state가 `middle`인 상태에서의 구현이 없어서 일단 이렇게 처리하신건가요?!

2023-10-01 04:47 UTC, kyw0716 commented on frontend/src/components/google-maps/marker/HighZoomMarkerContainer/hooks/useRenderStationMarker.tsx
> +  const removeAllMarkers = (prevMarkerInstances: StationMarkerInstance[]) => {
👍

2023-10-01 04:47 UTC, kyw0716 commented on frontend/src/components/google-maps/marker/LowZoomMarkerContainer/LowZoomMarkerContainer.tsx
> +const LowZoomMarkerContainer = () => {
그때 얘기했던 내용이긴 하지만 `useRegionMarkers` 훅 이름과 어울리게 `RegionMarkerContainer`로 하는게 더 좋을 것 같기도 하네요. 추후에 다시 얘기해봐도 좋을 것 같습니다!

2023-10-01 04:47 UTC, kyw0716 commented on frontend/src/components/google-maps/marker/LowZoomMarkerContainer/LowZoomMarkerContainer.tsx
> +  return regions.map((region) => <RegionMarkerRenderer key={region.regionName} region={region} />);
컴포넌트에서 map 함수가 반환하는 배열을 직접 리턴하는게 익숙하지 않은 방법이라 차라리 리턴값은 그냥 `<></>`로 고정하고 중간에서 `forEach`로 렌더링 로직을 돌리는 것도 괜찮을 것 같아요!

아니면 `RegionMarker`를 렌더링 하는 부분도 제가 작성한 마커 렌더링 훅에서 처리할 수 있도록 훅을 좀 확장해보는 것도 좋을 것 같습니다!

2023-10-01 04:47 UTC, kyw0716 commented on frontend/src/components/google-maps/marker/LowZoomMarkerContainer/components/RegionMarkerRenderer.tsx
> +const RegionMarkerRenderer = ({ region }: RegionMarkerProps) => {
예전 방식을 살린다고 했던 부분이 이 부분이었군요! 이 부분 나중에 캠퍼스에서 다시 얘기해봅시다

2023-10-01 04:47 UTC, kyw0716 commented on frontend/src/components/google-maps/marker/LowZoomMarkerContainer/hooks/useRegionMarkers.ts
> +      throw new Error('지역 마커를 수신을 실패했습니다.', error);
👍

2023-10-01 04:47 UTC, kyw0716 commented on frontend/src/components/google-maps/marker/LowZoomMarkerContainer/hooks/useRenderRegionMarker.tsx
> +export const useRenderRegionMarker = () => {
앞에서도 이야기 한 내용이지만 어차피 마커를 렌더링 하는 로직 자체는 동일한 메서드의 호출로만 이루어져서 마커 렌더링 관련 로직을 하나의 훅에서만 담당하도록 하는 것도 좋을 것 같아요!

2023-10-01 04:47 UTC, kyw0716 commented on frontend/src/components/google-maps/marker/MarkersContainers.tsx
> +import HighZoomMarkerContainer from './HighZoomMarkerContainer';
이것도 꼭 다시 얘기해봅시다

2023-10-01 04:47 UTC, kyw0716 commented on frontend/src/mocks/handlers/station-markers/stationMarkerHandlers.ts
> +  rest.get(`${DEVELOP_SERVER_URL}/stations/markers/regions`, async (req, res, ctx) => {
👍

2023-10-01 04:47 UTC, kyw0716 commented on frontend/src/stores/google-maps/googleMapStore.ts
> +  moveTo: (latLng: google.maps.LatLngLiteral, newZoom?: number) => {
👍

2023-10-01 04:52 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/map/CarFfeineListener.tsx
> +      warningModalActions.openModal(<ZoomWarningModal />);
네 맞습니다.
이 부분은 중간 단계 구현할 때 일부 개선이 있을 것 같아요

2023-10-01 04:53 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/marker/LowZoomMarkerContainer/LowZoomMarkerContainer.tsx
> +const LowZoomMarkerContainer = () => {
네

2023-10-01 04:57 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/marker/LowZoomMarkerContainer/LowZoomMarkerContainer.tsx
> +  return regions.map((region) => <RegionMarkerRenderer key={region.regionName} region={region} />);
저는 <></> 방식을 선호합니다만 이전에 야미의 리뷰를 받아 저 방식을 다시 채택했습니다

2023-10-01 05:00 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/marker/LowZoomMarkerContainer/components/RegionMarkerRenderer.tsx
> +const RegionMarkerRenderer = ({ region }: RegionMarkerProps) => {
이 부분은 한번 low 단계에 진입하면 재 요청이 발생하지 않아서 개별 생성을 하더라도 큰 이상이 없는 것 같습니다.
(1회 요청 시 전국 데이터를 한번에 다 받아오게 되어있습니다.)

또, 기존 로직에는 타입이 강하게 결합되어 있는 상황이라 제네릭을 도입하기 전 까지는 우선 레거시를 활용토록 했습니다.

2023-10-01 05:04 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/marker/MarkersContainers.tsx
> +import HighZoomMarkerContainer from './HighZoomMarkerContainer';
ㄴ[ㅔ

2023-10-01 07:31 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/marker/LowZoomMarkerContainer/hooks/useRenderRegionMarker.tsx
> +export const useRenderRegionMarker = () => {
이 부분은 이후에 논의하면서 개선해보는게 어떨까요?

2023-10-01 08:36 UTC, kyw0716 commented on frontend/src/components/google-maps/marker/LowZoomMarkerContainer/LowZoomMarkerContainer.tsx
> +  return regions.map((region) => <RegionMarkerRenderer key={region.regionName} region={region} />);
이 부분은 조금 더 얘기해보는게 좋겠네요!

2023-10-01 08:37 UTC, kyw0716 approved these changes

2023-10-01 08:39 UTC, merged