refactor: StationSummaryWindow의 구조를 개선한다
woowacourse-teams/2023-car-ffeine pull request #821
Opened 2023-10-01 05:24 UTC by gabrielyoon7

## 📄 Summary

<img width="347" alt="image" src="https://github.com/woowacourse-teams/2023-car-ffeine/assets/69189073/d45834c6-e657-40cd-8410-0022bb94978f">

### 🚨 이번 PR까지는 보여지는 결과가 동일합니다.

위 사진과 같이 기존과 같은 결과를 보여주도록 되어있습니다.

따라서 디자인이나 사용법은 이전과 완벽하게 동일합니다.

원래는 디자인 개선을 하려고 했는데, 스토리북 만들려고 사전작업 하다보니 이런 저런 생각이 많이 들어서 디자인은 하지 않고 개선 작업만 해서 PR을 날립니다.

주요 변경사항은 다음과 같습니다.

### 🙅‍♀️ 더이상 StationSummary에 의존하지 않습니다.

StationSummaryWindow 에서 StationInfoWindow로 이름을 바꿨습니다.

이전에 최적화 작업 중 바뀐 사항 중 하나는, StationSummaryWindow가 자체적으로 서버에서 summary데이터를 받아온다는 것이었습니다.

근데 꼭 summary 데이터를 받아와야 할까요? 어차피 details와 같은 정보가 아닐까요?

먼 거리의 마커 검색 시, 마커에 숫자를 렌더링 할 때 `details 정보를 참조하도록 한 개선 사항`을 이곳에도 반영했습니다!

참고로, 이 부분은 5차 데모데이 이후에 개선사항으로 센트가 작업했던 내용과 거의 비슷합니다.

### 🆕 개명했습니다.

StationSummaryWindow와 관련된 대부분의 이름들이 StationInfoWindow 으로 바뀌었습니다.
(단, 기존 좌측 리스트와 연관된 로직은 일절 변경하지 않았습니다.)

좌측 리스트에서만 사용하는 summary 관련 훅이나 코드들도 summary라는 용어를 사용중이고, 마커 위의 info window도 summary라는 용어를 사용중이었습니다.

하지만 이들은 더이상 서로 아무런 관계가 없습니다.

따라서 info window와 관련된 코드들의 이름을 전부 개명하였고, 심지어 직접 참조하는 api도 summary에서 detail로 옮겼습니다.

이는 이후 PR에 작업 할 `디자인 개선에서 활용할 예정`입니다.!

### 🙆‍♀️ 스토리북 추가

기존 컴포넌트를 최대한 유지하면서 스토리북을 구현하려고 하였으나, 도저히 커스텀 훅을 mocking 할 수 없었습니다.
스토리북 팀에서 제안하는 방식을 따르려면 라이브러리 설치 후, 절대경로 표기법을 포기해야 했습니다.
따라서 디자인용 infoWindow 컴포넌트를 하위로 분리하였고, 해당 컴포넌트는 스토리북에 등록했습니다.
덕분에 코드를 안전하게 분리하여 가독성이 좋아졌네요!
<img width="492" alt="image" src="https://github.com/woowacourse-teams/2023-car-ffeine/assets/69189073/50fbea69-914d-4460-b243-7844a55967fa">

### 3줄요약

1. infoWindow에 summary 라는 키워드를 붙여놔서 좌측 패널 리스트랑 넘 헷갈리는건 둘째치고, 서로 크게 연관도 없는 상태임!
2. 이제 infoWindow에서 summary가 아닌 detail로 api 를 쏘니깐 참고 바람
3. 하는 김에 스토리북도 추가해놓음. 잘했져?

## 🕰️ Actual Time of Completion

> 2시간

## 🙋🏻 More

>

2023-10-02 11:50 UTC, feb-dain requested changes

2023-10-02 11:50 UTC, feb-dain commented on frontend/src/components/ui/StationInfoWindow/StationInfo.stories.tsx
> +  //padding: 12px;
지워야 할 부분 인가여?? 😶

2023-10-02 11:50 UTC, feb-dain commented on frontend/src/components/ui/StationInfoWindow/StationInfo.tsx
> +    <ListItem tag="div" key={stationId} css={padding}>
ListItem 대신 Box나 다른 걸로 대체할 수 있을 것 같은데 (css padding 대신 pt, px, pb으로 대체) 이 부분은 원래 이렇게 되어있었을까요?? 여기 건드리는 김에 여기도 수정합시다!

2023-10-02 11:50 UTC, feb-dain commented on frontend/src/components/ui/StationInfoWindow/StationInfo.tsx
> +              css={companyNameText}
fontSize 속성 있습니다! css 대신 `fontSize`로 바꿔주세여~

2023-10-02 11:50 UTC, feb-dain commented on frontend/src/components/ui/StationInfoWindow/StationInfoWindow.tsx
> +import { useNavigationBar } from '@ui/Navigator/NavigationBar/hooks/useNavigationBar';
여기 폴더 구조는 나중에 센트가 건드린다고 했었죠??

2023-10-02 11:50 UTC, feb-dain commented on frontend/src/components/ui/StationInfoWindow/useFetchStationDetatils.ts
`useFetchStationDetatils.ts` -> `useFetchStationDetails.ts` 오타났으요

2023-10-02 11:50 UTC, feb-dain commented on frontend/src/components/ui/StationInfoWindow/useFetchStationDetatils.ts
> +  }, [stationId]);
[ 질문 ] `useStationDetails` 안 쓰고 이렇게 따로 만든 이유가 있나요??

2023-10-02 11:50 UTC, feb-dain commented on frontend/src/components/ui/StationInfoWindow/useFetchStationDetatils.ts
> +    fetchStationDetails(stationId).then((stationDetailsResponse) => {
리뷰하다가 발견했는데 `fetchStationDetails`를 `useStationCongestionStatistics.ts` 여기서도 똑같은 이름으로 쓰고 있네요 `useStationCongestionStatistics.ts` 여기서 사용하는 함수 이름을 바꿔야 할 것 같아요

2023-10-02 11:51 UTC, feb-dain commented
스토리북 잘했읍니다 굿굿 ㅋㅋㅋㅋ👍🏻

2023-10-02 14:24 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationInfoWindow/StationInfo.stories.tsx
> +  //padding: 12px;
이상하게 구글 지도 위에 그려진 원본 InfoWindow에는 적용되어있어서 혹시 몰라서 살려놨는데 그냥 제거하겠습니다

2023-10-02 14:29 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationInfoWindow/StationInfo.tsx
> +    <ListItem tag="div" key={stationId} css={padding}>
그렇네요

2023-10-02 14:31 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationInfoWindow/StationInfo.tsx
> +              css={companyNameText}
ne

2023-10-02 14:32 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationInfoWindow/StationInfoWindow.tsx
> +import { useNavigationBar } from '@ui/Navigator/NavigationBar/hooks/useNavigationBar';
여긴 안건드릴 것 같은데 잘 모르겠네요

2023-10-02 14:32 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationInfoWindow/useFetchStationDetatils.ts
네

2023-10-02 14:34 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationInfoWindow/useFetchStationDetatils.ts
> +  }, [stationId]);
`createRoot처리된엘리먼트.render(<리액트컴포넌트/>)`
마커에서 위와 같은 방식으로 React DOM을 생성하면 QueryClientProvider 의 범위에서 벗어나게 되는데요,
따라서 내부 컴포넌트에서 tanstack query 사용이 불가능합니다.

useStationDetails훅은 tanstack query를 사용중이므로 역시 사용이 불가능합니다

2023-10-02 14:35 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationInfoWindow/useFetchStationDetatils.ts
> +    fetchStationDetails(stationId).then((stationDetailsResponse) => {
그렇네요?

2023-10-02 14:58 UTC, kyw0716 requested changes
헷갈리는 이름을 잘 개선해주신 것 같습니다! 코드 읽어보고 혹시 문제가 되진 않을까 하는 부분이 있어 코멘트 남겼습니다! 확인 부탁드릴게요~

2023-10-02 14:58 UTC, kyw0716 commented on frontend/src/components/google-maps/marker/HighZoomMarkerContainer/hooks/useRenderStationMarker.tsx
> +        openStationInfoWindow(stationId, markerInstance);
👍

2023-10-02 14:58 UTC, kyw0716 commented on frontend/src/components/ui/StationInfoWindow/StationInfoWindow.tsx
> +  const { stationDetails, isLoading } = useFetchStationDetails(selectedStationId);
리스트에서 클릭한 충전소에 infoWindow를 띄우는 경우에 불필요한 detail 정보 재요청이 발생하지 않을까? 하는 생각이 드네요 혹시 이 부분 확인 부탁드립니다!

2023-10-02 14:58 UTC, kyw0716 commented on frontend/src/components/ui/StationInfoWindow/useFetchStationDetails.ts
> +export const useFetchStationDetails = (stationId: string) => {
useQuery를 StationInfoWindow안에서 호출해보는건 어떨까요?! 앞서 이야기 했던 문제가 실제로 발생한다면 요청 관련 훅을 새로 만들기 보단 useQuery를 사용하는 것이 더 좋을 것 같아서요!

2023-10-02 14:58 UTC, kyw0716 commented on frontend/src/stores/google-maps/stationInfoWindowStore.ts
> +interface StationInfoWindowStore {
👍

2023-10-02 15:06 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationInfoWindow/StationInfoWindow.tsx
> +  const { stationDetails, isLoading } = useFetchStationDetails(selectedStationId);
불필요한 재요청이 들어가는 것이 맞습니다.
기존에도 불필요한 summary 정보 재요청이 들어가고 있었는데, 이를 detail로 바꾼 것입니다.
이 컴포넌트가 `<QueryClientProvider/>`의 영역에서 벗어나는 상황이라 현재로써는 재활용이 어렵습니다.

다만, 굳이 summary를 detail로 바꾼 이유는 다음 PR에서 디자인 작업을 할 때 활용할 수 있는 데이터가 많아지는 것을 노렸습니다.

2023-10-02 15:07 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationInfoWindow/useFetchStationDetails.ts
> +export const useFetchStationDetails = (stationId: string) => {
위와 같습니다.

2023-10-02 15:28 UTC, kyw0716 commented on frontend/src/components/ui/StationInfoWindow/StationInfoWindow.tsx
> +  const { stationDetails, isLoading } = useFetchStationDetails(selectedStationId);
아하 캐시 데이터를 추가하는것도 안되는거였군요

2023-10-02 15:29 UTC, kyw0716 approved these changes

2023-10-03 01:15 UTC, feb-dain approved these changes

2023-10-03 01:19 UTC, feb-dain requested changes

2023-10-03 01:19 UTC, feb-dain commented on frontend/src/hooks/tanstack-query/station-details/useStationCongestionStatistics.ts
>    const stationDetails = await fetch(
여기는 그대로 stationDetails네요!
저는 확인 못했는데 받아오는 정보가 stationStatistics 맞나요??

2023-10-03 03:46 UTC, gabrielyoon7 commented on frontend/src/hooks/tanstack-query/station-details/useStationCongestionStatistics.ts
>    const stationDetails = await fetch(
빼먹었네요. 반영했습니다

2023-10-03 03:50 UTC, feb-dain approved these changes

2023-10-03 03:51 UTC, merged