refactor: 좌측 패널의 충전소 리스트의 사용성을 개선한다
woowacourse-teams/2023-car-ffeine pull request #824
Opened 2023-10-02 18:42 UTC by gabrielyoon7

## 📄 Summary

> 기존에 존재하는 버그를 수정하는 김에 구조도 개선했습니다.

<img width="1487" alt="image" src="https://github.com/woowacourse-teams/2023-car-ffeine/assets/69189073/7f30a3ae-b4cc-4a73-a90e-6c8af8503df4">

### 기존 구조

기존에는 화면 내에 존재하는 우측 마커의 아이디를 기준으로, 서버에 추가 요청을 보내 summary 정보를 받아왔었습니다.
이 과정에서 크게 다음과 같은 작업이 있었는데요

1. 신규 충전소 정보를 요청하기 전에 `캐시된 저장소`를 참조하여 알고 있는 충전소라면 제외(`uncachedStationSummaryIds`)하여 요청을 보낸다.
2. 새로운 데이터가 수신되면 `캐시된 저장소`에 저장한다.
3. 이 과정에서 useFetchStationSummaries 훅 내부의 어떤 상태(ex. 로딩)가 변경되어 재 렌더링을 유발하고, 재 렌더링 시 상태가 아닌 캐싱된 값을 강제로 읽어 충전소 리스트를 렌더링 한다. (2번에서 저장한 신규 데이터는 마치 캐시된 데이터 처럼 보이는 효과가 있었다.)

이 과정에서 3번은 굉장히 해석하기 어려운 존재였습니다.
특히 처음 보는 사람에게 렌더링 시점을 간접적으로 파악하게 하여 디버깅 시 가독성이 좋지 않았습니다.
따라서 해당 값을 상태로 두되, tanstack query에서 관리하도록 하였습니다.

### 새로운 구조

기존의 1,2번 과정은 동일합니다.
3. useInfitedQuery에는 신규 데이터들만 렌더링할 수 있는 상태를 가지게 됩니다.
4. 상태가 변경되었으므로 해당 부분을 페이지화 하여 재렌더링 합니다. (이 부분은 기존의 무한스크롤 훅의 개념과 동일합니다.)
5. 이 부분에 앞선 부분에 `캐시된 저장소`의 리스트를 먼저 보여주고, 이후에 useInfitedQuery의 data를 이어 붙여준다.

### 결과

이제 훅에서 무한스크롤을 관리해주므로 도중에 발생하는 딜레이 없이 정확하게 1번 요청이 순차적으로 들어가게 됩니다.
기존에 있던 버그(한번에 요청이 몰아서 들어가는 현상, 로딩중인지 확인하기 어려운 현상 등)는 모두 사라졌습니다.
따라서 디바운스도 제거할 수 있었습니다.

## 🕰️ Actual Time of Completion

> 3시간

## 🙋🏻 More

>

2023-10-03 06:04 UTC, kyw0716 requested changes
useInfiniteQuery를 도입하기 어려울 것이라 생각했는데 멋지게 도입해주셨네요👍 
useInfiniteQuery를 도입하면서 page 상태가 사라짐에 따라 이전에 포기했던 10개씩 충전소 목록을 새로 요청 넣는 방식을 이제는 도입할 수 있게 되었는데 아직 반영되지 않은 것 같아 이 부분 리뷰 남겼습니다. 확인 부탁드릴게요~

2023-10-03 06:04 UTC, kyw0716 commented on frontend/src/components/ui/StationListWindow/hooks/useInfiniteStationSummaries.ts
> +  return markers.reduce((acc: string[][], marker, index) => {
바뀐 방식에서 useInfiniteQuery 훅을 활용하기 때문에 이제는 stationIdChunks를 만들 때 filter로 미리 캐시된 정보를 제거해도 될 것 같습니다.

이전 방식에서는 
1. 캐시된 정보를 보여준다.
2. 충전소 마커 요청을 통해 받아온 정보로 stationIdChunks를 만든다.
3. 리스트의 끝에 닿으면 stationIdChunks의 page 인덱스에 해당하는 충전소 아이디로 충전소 목록 조회 요청을 발생시킨다.
4. page 상태에 1을 더해준다.
5. 위 과정을 반복한다.

위와 같은 과정을 통해 리스트를 보여줬으므로 stationIdChunks에서 미리 캐시 데이터를 제외하게 되면 page는 올라갔는데 stationIdChunks의 길이는 줄어든 상태로 요청을 발생시키게 되어 page와 stationIdChunks의 인덱스의 불일치로 인해 화면 내 모든 마커의 목록을 완성할 수 없었습니다. 그래서 어쩔 수 없이 새로운 요청을 10개씩 발생시키는 것을 포기하고 요청을 발생시키는 그 순간에 캐시 데이터에 지금 요청을 발생시킬 id가 포함되어 있는지 여부를 판별했었는데 이 방식이 이제는 불필요해보입니다.

현재 방식에서는
1. 캐시된 정보를 보여준다.
2. useInfiniteQuery를 통해 캐시되지 않은 정보들을 요청하고, 화면에 출력한다.

위와 같이 방식이 변경되었으므로 page와 stationIdChunks의 인덱스 간의 불일치가 발생하지 않을 것이므로

```suggestion
  return markers
    .filter((marker) => !cachedStationSummariesActions.has(marker.stationId))
    .reduce((acc: string[][], marker, index) => {
```
위와 같이 stationIdChunks를 만들 때 캐시데이터를 미리 제거해도 괜찮을 것 같습니다!

2023-10-03 06:04 UTC, kyw0716 commented on frontend/src/components/ui/StationListWindow/hooks/useInfiniteStationSummaries.ts
> +      }
앞선 리뷰에서 말씀 드린 것과 같이 이 부분에서도 요청을 넣기 직전에 캐시 데이터에 stationId가 존재하는지 여부를 판별하지 않고 stationIdChunks를 생성할 때 이를 미리 제거한 상태로 그냥 stationIds를 통해 요청을 발생시키는 것이 좋을 것 같습니다!

이렇게 되면 이전에 포기했던 10개씩 새로운 충전소 목록을 불러오는 것이 가능해질 것 같습니다!

```suggestion
      const stationIds = stationIdChunks[pageParam] ?? [];

      if (stationIds.length > 0) {
        const stationSummaries = await fetchStationSummaries(stationIds);
        cachedStationSummariesActions.add(stationSummaries);
        return { stations: stationSummaries, nextPage: pageParam + 1 };
      } else {
        return { stations: [], nextPage: -1 };
      }
```

2023-10-03 07:59 UTC, feb-dain requested changes

2023-10-03 07:59 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
`frontend/src/components/ui/StationListWindow/components/StationList.tsx` 

폴더 구조가 좀 이상해 보여서😂
이렇게 하는 건 어떤가요? 

```
📦StationListWindow
 ┣ 📂fallbacks
 ┃ ┣ 📜EmptyStationsNotice.tsx
 ┃ ┣ 📜StationListSkeletons.tsx
 ┃ ┣ 📜StationSummaryCardSkeleton.stories.tsx
 ┃ ┗ 📜StationSummaryCardSkeleton.tsx
 ┣ 📂hooks
 ┃ ┗ 📜useInfiniteStationSummaries.ts
 ┣ 📂tools
 ┃ ┗ 📜cachedStationSummaries.ts
 ┣ 📜index.ts
 ┣ 📜StationSummaryCard.tsx
 ┣ 📜StationList.tsx
 ┗ 📜StationListWindow.tsx
```

2023-10-03 07:59 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +    isLoading: isStationSummariesLoading,
`isStationSummariesLoading` 
👇🏻
`areStationSummariesLoading`이나 `isStationSummaryListLoading`이 좋을 것 같아요!

2023-10-03 07:59 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +  const isStationSummariesEmpty =
위 리뷰와 같습니다~

2023-10-03 07:59 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +  const isAvailableToFetchNextPage =
다음 page를 fetch할 수 있냐 없냐 여부를 물어보는 거 맞죠??

그럼 `canFetchNextPage` 이렇게 바꾸는 건 어떨까요?

2023-10-03 07:59 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +          Error: {JSON.stringify(error)}
<img width="160" alt="image" src="https://github.com/woowacourse-teams/2023-car-ffeine/assets/108778921/00a92256-fc4f-4d4e-976f-b18f36291186">

에러 메시지가 뜰 줄 알았는데 그냥 `{ }` 객체가 뜨네요! 의도한 동작이 맞나요??

2023-10-03 07:59 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +      ) : status === 'error' ? (
[질문] `isLoading, isError 대신 status === 'loading', 'error'`를 사용한 이유가 있을까요?

2023-10-03 07:59 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +      ) : (
`List` 컴포넌트 안에서 삼항 연산자 사용하는 것보다 바깥으로 빼는 게 더 가독성 좋을 것 같아요!

```tsx
  const renderContent = () => {
    if (status === 'loading') {
      return <StationListSkeletons />;
    }

    if (status === 'error') {
      return (
        <Text variant="caption" align="center">
          Error: {JSON.stringify(error)}
        </Text>
      );
    }

    return (
      <>
        {cachedStationSummaries.map((stationSummary) => (
          <StationSummaryCard key={stationSummary.stationId} station={stationSummary} />
        ))}
        {data.pages.map((page) =>
          page.stations.map((stationSummary) => (
            <StationSummaryCard key={stationSummary.stationId} station={stationSummary} />
          ))
        )}
        
        {isFetchingNextPage && <StationListSkeletons />}
        {isAvailableToFetchNextPage && <div ref={loadMoreElementRef} />}

        {isStationSummariesEmpty ? (
          <EmptyStationsNotice />
        ) : (
          isEndOfList && (
            <Text align="center" my={10}>
              주변의 모든 충전소를 불러왔습니다.
            </Text>
          )
        )}
      </>
    );
  };

  return <List css={searchResultList}>{renderContent()}</List>;
};
```
이런 방식은 어떤가요?

2023-10-03 07:59 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +          ))}
```suggestion
        {data.pages.map((page) =>
          page.stations.map((stationSummary) => (
            <StationSummaryCard key={stationSummary.stationId} station={stationSummary} />
          ))
        )}
```

2023-10-03 07:59 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +          {isStationSummariesEmpty ? ( // 첫 페이지에 아무것도 없을 때
주석 없어도 충분히 이해할 것 같아요!

2023-10-03 07:59 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +            )
```suggestion
            isEndOfList && (
              <Text align="center" my={10}>
                주변의 모든 충전소를 불러왔습니다.
              </Text>
            )
```

2023-10-03 07:59 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/hooks/useInfiniteStationSummaries.ts
> +        return { stations: stationSummaries, nextPage: pageParam + 1 };
return 위에 개행 넣어주세요~

2023-10-03 07:59 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +    <List css={searchResultList}>
`searchResultList` 여기는 아직 안 바뀌었네요😂
`stationListCss`로 바꿔도 될 것 같아요! 
(css 이름 컨벤션 -css 인 것도 있고 style이나 아무것도 안 붙인 것도 있던데 이것도 같이 정해봅시다 나중에
css 붙인 게 많아서 일단 여기선 css 붙이는 걸로 해요)

2023-10-03 08:00 UTC, feb-dain commented
굿굿 고생하셨슴다! 👍🏻

2023-10-03 13:23 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/hooks/useInfiniteStationSummaries.ts
> +  return markers.reduce((acc: string[][], marker, index) => {
아 그렇네요.
생각해보니 이로 인해서 항상 일정한 데이터를 요청하는 것이 아닌 불균형하게 들쑥날쑥 요청이 들어가던 문제도 덩달아 해결되겠군요

2023-10-03 13:25 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/hooks/useInfiniteStationSummaries.ts
> +      }
이해했습니다. 반영완료했어요

2023-10-03 13:30 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
네

2023-10-03 14:11 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +    isLoading: isStationSummariesLoading,
ne

2023-10-03 14:11 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +  const isStationSummariesEmpty =
ne

2023-10-03 14:12 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +  const isAvailableToFetchNextPage =
개인적으로는 boolean 변수는 되도록이면 is 또는 has 만 쓰는 것이 맞는 것 같습니다

2023-10-03 14:26 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +      ) : status === 'error' ? (
[공식 문서 예제](https://tanstack.com/query/v4/docs/react/examples/react/load-more-infinite-scroll)를 따라갔습니다.

2023-10-03 14:27 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +          Error: {JSON.stringify(error)}
이 질문은 슬랙에...

2023-10-03 14:31 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +  const isAvailableToFetchNextPage =
왜죠...? Boolean 변수명에 조동사를 쓰는 경우는 많고, 권장되는 사항이기도 합니다. Is, has만 쓰게 되면 오히려 가독성이 안 좋아지는 경우가 많습니다. 특히 지금 같은 변수명은 한 번에 이해하기 어려웠어요😂

<a href="https://soojin.ro/blog/naming-boolean-variables">naming-boolean-variables</a>

공원이 공유해준 네이밍 참고 링크인데요. 한번 읽어보시면 좋을 것 같습니다!

2023-10-03 17:12 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +      ) : (
반영했습니다

2023-10-04 01:00 UTC, kyw0716 approved these changes
반영하신거 확인했습니다! 고생하셨어요~

2023-10-04 02:03 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +          ))}
1. 불필요한 div태그로 인해 css가 제대로 먹을 수 없기는 합니다.
2. tanstack query 내부적으로 페이지 단위로 재렌더링을 시도하는 경우가 있기 때문에 키를 살려두는 것이 맞는 것 같음

```tsx
      {data.pages.map((page) => (
        <Fragment key={JSON.stringify(page.stations.map((station) => station.stationId))}>
          {page.stations.map((stationSummary) => (
            <StationSummaryCard key={stationSummary.stationId} station={stationSummary} />
          ))}
        </Fragment>
      ))}
```

따라서 Fragment를 적용합니다.

2023-10-04 02:07 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +            )
네

2023-10-04 02:08 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/hooks/useInfiniteStationSummaries.ts
> +        return { stations: stationSummaries, nextPage: pageParam + 1 };
네

2023-10-04 02:56 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +    <List css={searchResultList}>
네

2023-10-04 03:40 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +          ))}
StationSummaryCard의 key인 `stationSummary.stationId`가 고유하니까 바뀐 Card만 재렌더링 되지 않나요? Fragment에 stationId 배열을 key로 두면 하나만 바뀌어도 모든 Card들이 재렌더링 될텐데 이걸 의도한 걸까요??

2023-10-04 03:41 UTC, feb-dain commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +      ) : status === 'error' ? (
아무 이유없이 예제를 따라간 건가요?😂 왜 isLoading이랑 status === 'loading' 두 개가 공존해야 하는지 모르겠어요. 둘 중 하나로 통일하면 에러가 나나요?

2023-10-04 04:44 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +  const isAvailableToFetchNextPage =
반영했습니다

2023-10-04 05:05 UTC, gabrielyoon7 commented on frontend/src/components/ui/StationListWindow/components/StationList.tsx
> +          ))}
모릅니다

2023-10-04 05:19 UTC, feb-dain approved these changes

2023-10-04 05:19 UTC, merged