design: 서버 클러스터링 마커 디자인을 구현한다
woowacourse-teams/2023-car-ffeine pull request #842
Opened 2023-10-08 13:57 UTC by gabrielyoon7

## 📄 Summary

> 디자인만 미리 해놓습니다.

<img width="505" alt="image" src="https://github.com/woowacourse-teams/2023-car-ffeine/assets/69189073/3ae3e729-bedc-4644-9c4c-655f16f2a4fd">

아직 api endpoint 이름이 정해지지 않아서 컴포넌트 이름을 못정했습니다.
스토리북에서만 확인 가능합니다.

이후에 작업할 서버 클러스터링에서 활용할 예정입니다.

## 🕰️ Actual Time of Completion

> 10분

## 🙋🏻 More

>

2023-10-08 14:45 UTC, feb-dain requested changes

2023-10-08 14:45 UTC, feb-dain commented on frontend/src/components/google-maps/marker/MediumAreaMarkerContainer/components/FooMarker.stories.tsx
> +  component: FooMarker,
`FooMarker` ?! 😮😮😮😮
차라리 임시 이름이라도 `LargeDeltaAreaMarker` 이런 건 어떤가여

2023-10-08 14:45 UTC, feb-dain commented on frontend/src/components/google-maps/marker/MediumAreaMarkerContainer/components/FooMarker.stories.tsx
> +      description: '특정 영역의 충전소 갯수입니다.',
`개수`라고 해주세용

2023-10-08 14:45 UTC, feb-dain commented on frontend/src/components/google-maps/marker/MediumAreaMarkerContainer/components/FooMarker.stories.tsx
> +    <div style={{ width: 'fit-content' }}>
임시라지만 ;-; Box 컴포넌트 가져와서 `width="fit-content"` 해도 되지 않았을까요?!

2023-10-10 01:18 UTC, kyw0716 approved these changes

2023-10-10 01:18 UTC, kyw0716 commented on frontend/src/components/google-maps/marker/MediumAreaMarkerContainer/components/FooMarker.stories.tsx
> +  component: FooMarker,
네이밍이 상당히 맘에 드네요!

2023-10-13 04:04 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/marker/MediumAreaMarkerContainer/components/FooMarker.stories.tsx
> +      description: '특정 영역의 충전소 갯수입니다.',
네

2023-10-13 04:06 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/marker/MediumAreaMarkerContainer/components/FooMarker.stories.tsx
> +    <div style={{ width: 'fit-content' }}>
ne

2023-10-13 04:11 UTC, feb-dain approved these changes

2023-10-13 04:18 UTC, merged