feat: pull request 시 gradle test가 동작하도록 변경한다
woowacourse-teams/2023-car-ffeine pull request #85
Opened 2023-07-14 07:50 UTC by drunkenhw

[#15]

## 📄 Summary
> 아직 branch protection rule 은 설정하지 않았습니다. 이 PR이 merge 되면 protection rule을 설정하겠습니다.

## 🙋🏻 More
> 모르는 부분은 참고해주세요 열심히 정리했습니다~ 
https://car-ffeine.github.io/9

2023-07-14 07:55 UTC, be-student requested changes
https://devjem.tistory.com/76
나중에 gradle cache 도 해두면 좋을 것 같아요

2023-07-14 07:55 UTC, be-student commented on .github/workflows/backend-test-when-pr.yml
> +        run: ./gradlew build
build 대신 test 로 바꿔주면 좋을 것 같아요~

2023-07-14 07:55 UTC, be-student commented on .github/workflows/backend-test-when-pr.yml
> +      - develop
path 가 빠졌어요

2023-07-14 07:55 UTC, kiarakim approved these changes

2023-07-14 07:55 UTC, sosow0212 approved these changes
고쳐주시고 머지해주세요~

2023-07-14 07:55 UTC, sosow0212 commented on .github/workflows/backend-test-when-pr.yml
> +    name: merge-when-test
test-when-pr로 바꾸는게 어떨까요

2023-07-14 08:00 UTC, drunkenhw commented on .github/workflows/backend-test-when-pr.yml
> +      - develop
넣었습니다~

2023-07-14 08:01 UTC, drunkenhw commented on .github/workflows/backend-test-when-pr.yml
> +        run: ./gradlew build
수정했습니다~

2023-07-15 06:33 UTC, be-student approved these changes
이 부분만 변경해주세요

2023-07-15 06:33 UTC, be-student commented on .github/workflows/backend-test-when-pr.yml
> +        run: ./gradlew build
이 부분이 변경되지 않은 것 같아요...

2023-07-15 06:35 UTC, merged