refactor: msw용 mocking 데이터 생성 구조를 개선한다
woowacourse-teams/2023-car-ffeine pull request #857
Opened 2023-10-13 14:35 UTC by gabrielyoon7

## 📄 Summary

원래는 실데이터를 연결하려고 하였으나, webpack 기능의 한계로 인해 포기합니다.

어떤 부분이 문제인지는 이미 구두로 공유하였으나 문서화를 합니다.

- 실데이터를 msw 스펙에 맞춰 제작하면 97MB다.
- 실데이터를 외부에서 받아오는 경우 ❌
  - 캐시 처리를 하더라도 네트워크 지연시간을 감당할 수 없음
- 실데이터를 직접 내부에 넣는 경우 ✅
  - 초기 세팅이 굉장히 복잡해짐
  - 실데이터를 넣지 않은 경우를 고려해야함 ✅
    - dynamic import로 json을 넣을 수 있는가? ✅
    - webpack이 dynamic import를 지원하는가? ✅
    - 실 데이터 파일이 전혀 존재하지 않은 경우를 대응할 수 있는가? ❌

webpack에서 import를 하는 시점에 해당 파일이 존재하지 않는다면 오류를 출력합니다.
심지어 컴파일에 성공하여 웹앱이 정상 동작하더라도 오류가 출력되어 개발에 굉장한 방해가 됩니다.

결국 그냥 작업을 중단하고 코드 리팩터링 한 것만 올립니다.

## 🕰️ Actual Time of Completion
 
> 5시간

## 🙋🏻 More

>

2023-10-14 05:17 UTC, feb-dain requested changes

2023-10-14 05:17 UTC, feb-dain commented on frontend/src/mocks/data/congestions.ts
> +  const hasOnlyQuickChargers = foundStation.chargers.every(
마지막에 `-s` 빼주세욤

2023-10-14 05:17 UTC, feb-dain commented on frontend/src/mocks/data/reviews.ts
> +        '비매너 사용자들이 많아요비매너 사용자들이 많아요비매너 사용자들이 많아요비매너 사용자들이 많아요비매너 사용자들이 많아요비매너 사용자들이 많아요',
띄어쓰기 하는 것이 어떤가여!

2023-10-14 05:17 UTC, feb-dain commented on frontend/src/mocks/data/search.ts
> +    );
다른 곳에서 onlyCapacity를 안 쓰고 있는 것 같아서 이건 어떤가요
```suggestion
  const speed = chargers.map(({ capacity }) => capacity >= 
    QUICK_CHARGER_CAPACITY_THRESHOLD ? 'QUICK' : 'STANDARD'
  );
```

2023-10-14 05:17 UTC, feb-dain commented on frontend/tsconfig.json
> +    "resolveJsonModule": true
[질문] 이걸 추가한 이유는 무엇인가요?

2023-10-14 07:50 UTC, kyw0716 commented
혹시 ignore loader는 사용해보셨나요? PR에 해당 부분에 대해서는 언급이 없어서요! 추천은 드렸지만 잘 모르는 패키지라 원하는 기능을 수행하는 패키지가 아닌것인지 궁금합니다!!

2023-10-14 17:36 UTC, gabrielyoon7 commented
> 혹시 ignore loader는 사용해보셨나요? PR에 해당 부분에 대해서는 언급이 없어서요! 추천은 드렸지만 잘 모르는 패키지라 원하는 기능을 수행하는 패키지가 아닌것인지 궁금합니다!!

개발 도중에 이슈 주제를 변경하여 테스트 하지 않았었는데, 궁금함ㅁ이 생겨서 직접 해보았습니다.

결론부터 말씀드리면 세팅이 안됩니다

<img width="1709" alt="image" src="https://github.com/woowacourse-teams/2023-car-ffeine/assets/69189073/323203fe-9675-4815-a07b-09d4d8edb59a">

어쩌면 2016년도에 작성된 라이브러리라 더이상 호환이 안되는것일수도 있을 것 같네요 ㅠ

2023-10-14 17:36 UTC, gabrielyoon7 commented on frontend/tsconfig.json
> +    "resolveJsonModule": true
json을 import하려면 필요했었는데 더이상 필요하지 않으니 제거하겠습니다?

2023-10-14 17:51 UTC, gabrielyoon7 commented
> 혹시 ignore loader는 사용해보셨나요? PR에 해당 부분에 대해서는 언급이 없어서요! 추천은 드렸지만 잘 모르는 패키지라 원하는 기능을 수행하는 패키지가 아닌것인지 궁금합니다!!

방금 댓글 달았던거 삭제했습니다. 정정합니다.
제대로 된 세팅을 통해 테스트에 성공했습니다. (웹팩 구조가 라이브러리 설명과 살짝 달라서 잘못 세팅되었던 문제였네요.)

하지만 결과는 동일하네요 ㅠ

<img width="1470" alt="image" src="https://github.com/woowacourse-teams/2023-car-ffeine/assets/69189073/82dc00a5-5e1e-42c9-aa73-dbc865132ae5">

2023-10-14 17:57 UTC, gabrielyoon7 commented on frontend/src/mocks/data/congestions.ts
> +  const hasOnlyQuickChargers = foundStation.chargers.every(
변수 이름 "hasOnlyStandardChargers"와 "hasOnlyQuickChargers"는 충전소에 완속 충전기만 있는지 또는 급속 충전기만 있는지 확인하는 조건을 나타내는데요, 이 경우 복수형은 하나의 충전기만이 아닌 `여러 충전기에 대해 조건이 사실인지`를 나타내는 boolean이므로 -s를 붙이는 것이 적합하다고 생각합니다.

2023-10-14 18:00 UTC, gabrielyoon7 commented on frontend/src/mocks/data/reviews.ts
> +        '비매너 사용자들이 많아요비매너 사용자들이 많아요비매너 사용자들이 많아요비매너 사용자들이 많아요비매너 사용자들이 많아요비매너 사용자들이 많아요',
반영했습니다

2023-10-14 18:03 UTC, gabrielyoon7 commented on frontend/src/mocks/data/search.ts
> +    );
오 맵핑을 한번 더 줄일 수 있었군요

2023-10-14 18:04 UTC, gabrielyoon7 commented on frontend/src/mocks/data/search.ts
> +    );
반영했습니다

2023-10-15 03:03 UTC, feb-dain commented on frontend/src/mocks/data/congestions.ts
> +  const hasOnlyQuickChargers = foundStation.chargers.every(
여러 충전기 보다는 급속만 있는지 완속만 있는지를 확인하는게 주요하다고 생각해서 단수로 고쳐달라고 한 것이었습니다! 만약 가브리엘 의견이 그렇다면 has도 have로 바꿔야하지 않을까요?? 영문법상 단수 복수 맞춰야할 것 같아서요..!

2023-10-15 08:05 UTC, gabrielyoon7 commented on frontend/src/mocks/data/congestions.ts
> +  const hasOnlyQuickChargers = foundStation.chargers.every(
foundStation hasOnlyStandardChargers

라면 단수가 맞지 않을까요?

Chargers는 복수지만 foundStation은 단수니깐요

2023-10-15 08:09 UTC, gabrielyoon7 commented on frontend/src/mocks/data/congestions.ts
> +  const hasOnlyQuickChargers = foundStation.chargers.every(
+ only가 단수를 의미하지는 않습니다

2023-10-15 09:44 UTC, feb-dain commented on frontend/src/mocks/data/congestions.ts
> +  const hasOnlyQuickChargers = foundStation.chargers.every(
only가 단수를 의미하지 않는 건 압니다ㅋㅋㅋㅋ '이것`만` 가지고 있니'라는 의미가 있어서 충분하다고 생각했던 것 뿐입니다. 아 그러네요 주어가 저기선 하나의 station이군요. 이해했습니다

2023-10-15 09:52 UTC, feb-dain approved these changes

2023-10-15 10:07 UTC, kyw0716 approved these changes
오프라인으로 함께 논의 해봤으니 어프루브 하겠습니다!

2023-10-15 10:13 UTC, merged