refactor: 서버 클러스터 마커 디자인을 개선합니다.
woowacourse-teams/2023-car-ffeine pull request #876
Opened 2023-10-17 09:05 UTC by gabrielyoon7

## 📄 Summary

> 서버 클러스터 마커 디자인을 개선합니다.

일단 시안성 확보만 했습니다.

원 크기가 줄었습니다.

테두리 색상 넣었습니다.

코드 리팩터링도 살짝 했습니다.

## 🕰️ Actual Time of Completion

> 1시간

## 🙋🏻 More

>

2023-10-17 09:55 UTC, feb-dain requested changes

2023-10-17 09:55 UTC, feb-dain commented on frontend/src/components/common/FlexBox/FlexBox.style.ts
> +      typeof $borderRadius === 'number' ? `${$borderRadius}px` : `${$borderRadius};`
FlexBox에 이거 안 만들어도 borderRadius 될텐데 안되나요? 

(+) 확인해보니 되네요. 관련 로직 없애주세요. borderRadius 속성 있습니다😂 FlexBox 사용할때 b만 쳐봐도 자동완성으로 속성이 있는지 없는지 확인할 수 있어요. 그리고 속성에 호버하면 관련 설명 볼 수 있습니다!

2023-10-17 09:55 UTC, feb-dain commented on frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/components/ClusterMarker.tsx
> +      css={{ border: '1px solid #3366FF' }}
border 속성 없나요? border 주고 borderWidth bordercolor 지정해주면 될 것 같은데

2023-10-17 09:55 UTC, feb-dain commented on frontend/src/types/stations.ts
> +export interface ClusterMarkerType {
왜 interface인데 타입이 붙었죠?? 컨벤션이랑 안 맞는 거 같아요

2023-10-17 09:59 UTC, gabrielyoon7 commented on frontend/src/types/stations.ts
> +export interface ClusterMarkerType {
타입 이름이 컴포넌트 이름이랑 겹칩니다.

기존 FooMarker에서 ClusterMarker로 바뀌었기 때문이죠.

2023-10-17 10:18 UTC, feb-dain commented on frontend/src/types/stations.ts
> +export interface ClusterMarkerType {
겹치는 건 봤습니다! Type을 붙이는 게 아니라 다른 이름을 해야하지 않을까요?? `ClusterMarkerInfo`, `ClusterMarkerCoordinates` 이런식으로 바꾸는 건 어떤가요?

2023-10-17 10:59 UTC, kyw0716 approved these changes
굿샷

2023-10-17 11:37 UTC, gabrielyoon7 commented on frontend/src/types/stations.ts
> +export interface ClusterMarkerType {
다른거 생각해보겠음니다

2023-10-18 02:23 UTC, gabrielyoon7 commented on frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/components/ClusterMarker.tsx
> +      css={{ border: '1px solid #3366FF' }}
수정반영하였습니ㅏㄷ

2023-10-18 02:23 UTC, gabrielyoon7 commented on frontend/src/components/common/FlexBox/FlexBox.style.ts
> +      typeof $borderRadius === 'number' ? `${$borderRadius}px` : `${$borderRadius};`
수정반영하였습니ㅏㄷ

2023-10-18 02:52 UTC, gabrielyoon7 commented on frontend/src/types/stations.ts
> +export interface ClusterMarkerType {
ClusterMarkerInfo는 불용어가 들어가서 안됩니다.
ClusterMarkerCoordinates는 위치 정보 뿐만이 아니라 충전기 개수도 들어가야 하는 상황이라 맞지 않는 이름입니다.

ClusterMarkerInterface으로 개명합니다

2023-10-18 03:03 UTC, feb-dain commented on frontend/src/types/stations.ts
> +export interface ClusterMarkerType {
count도 들어가는군요 리뷰할 때 못봤네요

근데 저희 interface 타입은 뒤에 interface 붙이지 않기로 했는데 얘만 있는 게 통일성을 해치는 것 같습니다. 다른 이름을 생각해보는 건 어떤가요. 예시를 든 것처럼 타입이나 인터페이스를 붙이는 것이 아닌 다른 이름을 생각해보라는 거였는데 인터페이스를 붙이다니 당황스럽군요 심지어 컨벤션으로 안 붙이기로 했는데 말이죠😂 ClusterMarkerRequirements 는 어떤가요?

2023-10-18 03:06 UTC, feb-dain commented on frontend/src/components/google-maps/marker/LargeDeltaAreaMarkerContainer/components/ClusterMarker.tsx
> +      css={{ border: '1px solid #3366FF' }}
```suggestion
border
```

border={true} 생략 가능합니다!

2023-10-18 04:11 UTC, gabrielyoon7 commented on frontend/src/types/stations.ts
> +export interface ClusterMarkerType {
안됩니다

2023-10-18 04:13 UTC, feb-dain approved these changes

2023-10-18 04:13 UTC, merged