feat: 마커 클러스터링을 한다
woowacourse-teams/2023-car-ffeine pull request #880
Opened 2023-10-18 09:05 UTC by kiarakim

## 📄 Summary

> 마커 클러스터링 기능 추가

## 🕰️ Actual Time of Completion

>

## 🙋🏻 More

>

2023-10-18 10:07 UTC, sosow0212 requested changes
작업하시느라 수고하셨습니다!

다만 이런 작업을 할 때 pr 메시지로 어떤 작업을 한 건지 상세하게 적어주시면 좋을 것 같아요 ㅠㅠ

클러스터링 기능 추가인 것은 알겠지만.. 구체적으로 어떤 방식으로 진행한 건지 있으면 더 좋을 것 같아요!

몇 가지만 수정해주세요~
클러스터링 어려운 작업이었을텐데 고생 많으셨습니다~ 👍

2023-10-18 10:07 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/domain/station/Grid.java
> +    private List<Point> points;
세 필드에 final을 붙일 수 있지 않나요?

2023-10-18 10:07 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationService.java
> -    @Scheduled(cron = "0 0/10 * * * *")
스케쥴링을 제거한 이유가 있나요?

2023-10-18 10:07 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridService.java
> +@RequiredArgsConstructor
해당 클래스에서 기본 생성자가 필요하지 않아 보입니다!

2023-10-18 10:07 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridService.java
> +
불필요한 개행 제거해주세요

2023-10-18 10:07 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridCacheService.java
> +                .toList();
이게 어떤 행위인지 메서드 분리를 통해 명시해주는 건 어떨까요?
이해하는데 한참 걸렸네요 ㅠ

2023-10-18 10:07 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridFacadeService.java
> +        List<GridWithCount> list = grids.stream()
`grids.stream()..` 로직이 중복되어 보입니다 메서드로 분리해주면 더 보기 좋을 것 같아요

2023-10-18 10:07 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/station/domain/station/GridGeneratorTest.java
> +    void 좌표_2개로_구역을_나눠준다() {
모든 테스트에 `given - when - then`이 빠져 있습니다 ㅠ

2023-10-18 10:07 UTC, sosow0212 commented on backend/src/test/java/com/carffeine/carffeine/station/service/station/StationGridServiceTest.java
> +
불필요한 개행이 있습니다~

2023-10-18 10:07 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/dto/GridWithCount.java
> +        BigDecimal centerLatitude = grid.getTop().getLatitude().add(grid.getBottom().getLatitude()).divide(BigDecimal.valueOf(2), 4, RoundingMode.CEILING);
체이닝이 너무 긴데, 가독성을 위해서 개행을 추가하거나 어떤 행위를 하는지 메서드로 분리해주시면 안될까요 혹은 `grid`안에 메서드로 뺄 순 없을까요?

2023-10-18 10:07 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridFacadeService.java
> +            stationGridService.assignStationGrids(grids, stationPoint);
아~ 모든 충전소를 꺼내서 Grid로 구역을 나눠주는 로직이었군요!

2023-10-18 13:57 UTC, drunkenhw requested changes

2023-10-18 13:57 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridFacadeService.java
> +            CompletableFuture<Void> future = CompletableFuture.runAsync(() -> stationGridService.assignStationGrids(grids, stationPoints), executor);
이 작업에 computablefuture를 사용한 이유가 있을까요? 무엇때문에 사용했는지 궁금합니다

저는 저 클래스에 대해 잘 모르기 때문에 사용 이유를 알고 싶어요

2023-10-18 13:57 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/station/domain/station/Point.java
> +@Embeddable
필요 없는 어노테이션인 것 같아요 그리고 해당 객체를 불변으로 만들어주면 좋을 것 같아요

2023-10-19 08:31 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/station/Grid.java
> +    private List<Point> points;
final 좋네요 감사합니다~

2023-10-19 08:31 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/domain/station/Point.java
> +@Embeddable
네에

2023-10-19 08:31 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridCacheService.java
> +                .toList();
아이코.. 메서드 분리하고 이름도 적절하게 명시했습니다!

2023-10-19 08:31 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridService.java
> +
네엡!

2023-10-19 08:31 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridService.java
> +@RequiredArgsConstructor
그렇네여. 감사합니다

2023-10-19 08:31 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridFacadeService.java
> +        List<GridWithCount> list = grids.stream()
넵넵

2023-10-19 08:31 UTC, kiarakim commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/dto/GridWithCount.java
> +        BigDecimal centerLatitude = grid.getTop().getLatitude().add(grid.getBottom().getLatitude()).divide(BigDecimal.valueOf(2), 4, RoundingMode.CEILING);
grid로 메서드를 뺐습니다!

2023-10-19 08:31 UTC, kiarakim commented on backend/src/test/java/com/carffeine/carffeine/station/domain/station/GridGeneratorTest.java
> +    void 좌표_2개로_구역을_나눠준다() {
추가했습니다!

2023-10-19 08:46 UTC, sosow0212 approved these changes
수고하셨습니다!

다만 한 번에 뜻을 알기 힘든 부분이 있는데요.
사실 몇 번 보면 이해는 할 수 있지만 그래도 가급적이면 Merge 전에 해당 부분을 메서드 분리로 뜻을 명시해주시면 좋을 것 같아요.

수고하셨습니다 👍

2023-10-19 08:46 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/domain/station/Grid.java
> +        return topLatitude.add(bottomLatitude).divide(BigDecimal.valueOf(2), 4, RoundingMode.CEILING);
이 부분도 어떤 로직인지 한 눈에 보이지가 않아요 ㅠ
한 번 더 메서드 분리 해서 어떤 행위인지 뜻을 부여해주면 좋을 것 같아요

2023-10-19 08:46 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/domain/station/Grid.java
> +        return topLongitude.add(bottomLongitude).divide(BigDecimal.valueOf(2), 4, RoundingMode.CEILING);
여기도 마찬가지입니다!

2023-10-19 08:46 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/station/service/station/StationGridCacheService.java
> +        if (lowerBound == NO_LATITUDE_FOUND || upperBound == NO_LATITUDE_FOUND) {
훨씬 보기 좋아졌네요! 👍

2023-10-26 15:31 UTC, drunkenhw approved these changes

2023-10-26 15:31 UTC, merged