chore: 일부 dependencies를 devDependencies로 이전한다
woowacourse-teams/2023-car-ffeine pull request #905
Opened 2023-10-25 16:17 UTC by gabrielyoon7

[#904]

## 📄 Summary

> 7월 배포당시 발생했던 문제로 인해 devDependencies의 일부 패키지를 dependencies에 옮겨놨었는데, 원복합니다.

## 🕰️ Actual Time of Completion

> 5분

## 🙋🏻 More

>

2023-10-25 16:48 UTC, kyw0716 requested changes
<img width="621" alt="image" src="https://github.com/woowacourse-teams/2023-car-ffeine/assets/77326660/a1f5496c-12f7-47ec-8720-6a34794fda91">

이번 PR의 문제는 아닌 것 같은데 `yarn build-dev`를 수행했을 때 `FlexBox` 컴포넌트의 `onClick` props의 타입추론이 제대로 되지 않는 문제가 있는 것 같네요 ㅠ 혹시 수정해주실 수 있나요? 

혹시 작업 시간이 애매하다 싶으면 제가 따로 이슈 파서 해도 괜찮습니다!

2023-10-25 16:53 UTC, gabrielyoon7 commented
> <img alt="image" width="621" src="https://user-images.githubusercontent.com/77326660/278086475-a1f5496c-12f7-47ec-8720-6a34794fda91.png">
> 이번 PR의 문제는 아닌 것 같은데 `yarn build-dev`를 수행했을 때 `FlexBox` 컴포넌트의 `onClick` props의 타입추론이 제대로 되지 않는 문제가 있는 것 같네요 ㅠ 혹시 수정해주실 수 있나요?
> 
> 혹시 작업 시간이 애매하다 싶으면 제가 따로 이슈 파서 해도 괜찮습니다!

안그래도 #903에서 발견해서 다 고쳐놨는데 여기에도 해놓겠습니다.
코드 중 두 곳이 저렇게 되어있더라구요.
바로 반영하겠습니다.

2023-10-25 17:10 UTC, kyw0716 approved these changes
고생하셨어요~~ 추가로 다음에 `FlexBox` 컴포넌트 자체에서 `onClick` props의 인자에 타입이 추론될 수 있도록 하는 것도 좋을 것 같아요!

2023-10-26 00:10 UTC, feb-dain approved these changes

2023-10-26 01:19 UTC, merged