fix: 폰트 preload 에러를 개선한다
woowacourse-teams/2023-car-ffeine pull request #909
Opened 2023-10-26 06:09 UTC by kyw0716

## 📄 Summary
preload에 다른 설정도 추가해줘야 제대로 동작하는 것을 확인해 해당 설정을 추가해주었습니다.

## 🕰️ Actual Time of Completion
1분

## 🙋🏻 More
[참고링크](https://stackoverflow.com/questions/50824181/preloading-google-fonts)

2023-10-26 06:26 UTC, gabrielyoon7 approved these changes
고생하셨습니다

2023-10-26 08:30 UTC, feb-dain requested changes

2023-10-26 08:30 UTC, feb-dain commented on frontend/public/index.html
>      />
```suggestion
<link
      href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700&display=swap"
      rel="preload"
      as="style"
      onload=“this.onload=null; this.rel=‘stylesheet’”
    />
```

혹시 링크 두 개 대신 이렇게 해도 되는지 확인해줄 수 있나요??

2023-10-27 07:56 UTC, feb-dain approved these changes

2023-10-28 15:02 UTC, merged