feat: 서비스 Key 자동 선택 기능 추가
woowacourse-teams/2023-car-ffeine pull request #97
Opened 2023-07-16 04:13 UTC by kiarakim

## 📄 Summary
> RandomKeySelector에 정팩메 만들어서 key 값 가져왔는데 어색한 부분 있으면 알려주십셔...! RandomKeySelector 얘도 레코드로 할 수 있는건지 잘 몰라서.. 레코드 명 괄호 안에 필드 들어간대서 ThreadLocalRandom넣어도 봤는데 그럼 이거 불러오는 RestTemplateChargeStationRequester에서 주입해주는건가 궁금합니다. 리뷰하면서 알려주심 감사하겠습니다

## 🙋🏻 More
>

2023-07-16 04:18 UTC, drunkenhw requested changes
고생하셨습니디 리뷰 남겼습니다!

2023-07-16 04:18 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/service/chargerStation/dto/RandomKeySelector.java
> +    }
이 클래스를 빈으로 등록하면 좋을 것 같아요!
```suggestion
@Component
public class RandomKeySelector {

    private static final ThreadLocalRandom threadLocalRandom = ThreadLocalRandom.current();

    @Value("${api.service_key}")
    private List<String> serviceKeys;

    public String generateRandomKey() {
        int randomNumber = threadLocalRandom.nextInt(0, 7);
        return serviceKeys.get(randomNumber);
    }
```

2023-07-16 04:18 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
> +        String serviceKey = RandomKeySelector.generateRandomKey();
그리고 이 클래스에서 주입받으면 좋을 것 같아요

2023-07-16 05:13 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/infra/api/RestTemplateChargeStationRequester.java
>      private final RestTemplate restTemplate;
클래스와 전역변수 사이에 한 칸의 개행을 주는 것은 어떨까요?

2023-07-16 05:13 UTC, sosow0212 commented on backend/src/main/java/com/carffeine/carffeine/service/chargerStation/dto/RandomKeySelector.java
> +        int randomNumber = threadLocalRandom.nextInt(0, 7);
매직넘버 상수화 해주면 더 좋을 것 같아요!

2023-07-16 05:15 UTC, drunkenhw commented on backend/src/main/java/com/carffeine/carffeine/service/chargerStation/dto/RandomKeySelector.java
> +        int randomNumber = threadLocalRandom.nextInt(0, 7);
```suggestion
        int randomNumber = threadLocalRandom.nextInt(0, serviceKeys.size());
```
하면 깔끔할 것 같아요

2023-07-16 05:23 UTC, sosow0212 requested changes
코드 컨벤션 위주로 확인해봤습니다~

2023-07-16 10:57 UTC, be-student approved these changes
박스터가 너무 잘 해줬네요 👍 
gitignore 에 mysql 디렉토리만 빼도록 넣어주면 좋을 것 같아요 👍 
고생 많으셨어요

2023-07-17 05:04 UTC, sosow0212 approved these changes
작업하시느라 수고하셨습니다 👍

2023-07-17 05:09 UTC, drunkenhw approved these changes
수고하셨습니다

2023-07-17 05:29 UTC, merged